# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/admin/last_validations.proto

require 'google/protobuf'

require 'isuxportal/resources/instance_command_execute_request_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/admin/last_validations.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.services.admin.TriggerEnvCheckRequest" do
    end
    add_message "isuxportal.proto.services.admin.TriggerEnvCheckResponse" do
    end
    add_message "isuxportal.proto.services.admin.TriggerInstanceRestartRequest" do
    end
    add_message "isuxportal.proto.services.admin.TriggerInstanceRestartResponse" do
    end
    add_message "isuxportal.proto.services.admin.ListInstanceCommandExecuteRequestsRequest" do
    end
    add_message "isuxportal.proto.services.admin.ListInstanceCommandExecuteRequestsResponse" do
      repeated :requests, :message, 1, "isuxportal.proto.resources.InstanceCommandExecuteRequest"
    end
    add_message "isuxportal.proto.services.admin.GetInstanceCommandExecuteRequestRequest" do
      optional :id, :int64, 1
    end
    add_message "isuxportal.proto.services.admin.GetInstanceCommandExecuteRequestResponse" do
      repeated :results, :message, 1, "isuxportal.proto.resources.InstanceCommandExecuteRequestResult"
    end
    add_message "isuxportal.proto.services.admin.GetInstanceCommandExecuteRequestOutputRequest" do
      optional :id, :int64, 1
    end
    add_message "isuxportal.proto.services.admin.GetInstanceCommandExecuteRequestOutputResponse" do
      optional :output, :string, 1
    end
  end
end

module Isuxportal
  module Proto
    module Services
      module Admin
        TriggerEnvCheckRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.TriggerEnvCheckRequest").msgclass
        TriggerEnvCheckResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.TriggerEnvCheckResponse").msgclass
        TriggerInstanceRestartRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.TriggerInstanceRestartRequest").msgclass
        TriggerInstanceRestartResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.TriggerInstanceRestartResponse").msgclass
        ListInstanceCommandExecuteRequestsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.ListInstanceCommandExecuteRequestsRequest").msgclass
        ListInstanceCommandExecuteRequestsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.ListInstanceCommandExecuteRequestsResponse").msgclass
        GetInstanceCommandExecuteRequestRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.GetInstanceCommandExecuteRequestRequest").msgclass
        GetInstanceCommandExecuteRequestResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.GetInstanceCommandExecuteRequestResponse").msgclass
        GetInstanceCommandExecuteRequestOutputRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.GetInstanceCommandExecuteRequestOutputRequest").msgclass
        GetInstanceCommandExecuteRequestOutputResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.GetInstanceCommandExecuteRequestOutputResponse").msgclass
      end
    end
  end
end
