# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/admin/last_validations.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/admin/last_validations.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.services.admin.TriggerEnvCheckRequest" do
    end
    add_message "isuxportal.proto.services.admin.TriggerEnvCheckResponse" do
    end
  end
end

module Isuxportal
  module Proto
    module Services
      module Admin
        TriggerEnvCheckRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.TriggerEnvCheckRequest").msgclass
        TriggerEnvCheckResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.TriggerEnvCheckResponse").msgclass
      end
    end
  end
end
