# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isuxportal/services/admin/unprepared_stats.proto

require 'google/protobuf'

require 'isuxportal/resources/team_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("isuxportal/services/admin/unprepared_stats.proto", :syntax => :proto3) do
    add_message "isuxportal.proto.services.admin.GetSSHKeyStatsQuery" do
    end
    add_message "isuxportal.proto.services.admin.GetSSHKeyStatsResponse" do
      repeated :items, :message, 1, "isuxportal.proto.services.admin.GetSSHKeyStatsResponse.SSHKeyUnregisteredTeam"
    end
    add_message "isuxportal.proto.services.admin.GetSSHKeyStatsResponse.SSHKeyUnregisteredTeam" do
      optional :team, :message, 1, "isuxportal.proto.resources.Team"
      repeated :unregistered_member_ids, :int64, 2
    end
    add_message "isuxportal.proto.services.admin.GetDiscordStatsQuery" do
    end
    add_message "isuxportal.proto.services.admin.GetDiscordStatsResponse" do
      repeated :items, :message, 1, "isuxportal.proto.services.admin.GetDiscordStatsResponse.DiscordNotJoinedTeam"
    end
    add_message "isuxportal.proto.services.admin.GetDiscordStatsResponse.DiscordNotJoinedTeam" do
      optional :team, :message, 1, "isuxportal.proto.resources.Team"
      repeated :not_joined_member_ids, :int64, 2
    end
    add_message "isuxportal.proto.services.admin.GetEnvCheckStatsQuery" do
    end
    add_message "isuxportal.proto.services.admin.GetEnvCheckStatsResponse" do
      repeated :items, :message, 1, "isuxportal.proto.resources.Team"
    end
  end
end

module Isuxportal
  module Proto
    module Services
      module Admin
        GetSSHKeyStatsQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.GetSSHKeyStatsQuery").msgclass
        GetSSHKeyStatsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.GetSSHKeyStatsResponse").msgclass
        GetSSHKeyStatsResponse::SSHKeyUnregisteredTeam = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.GetSSHKeyStatsResponse.SSHKeyUnregisteredTeam").msgclass
        GetDiscordStatsQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.GetDiscordStatsQuery").msgclass
        GetDiscordStatsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.GetDiscordStatsResponse").msgclass
        GetDiscordStatsResponse::DiscordNotJoinedTeam = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.GetDiscordStatsResponse.DiscordNotJoinedTeam").msgclass
        GetEnvCheckStatsQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.GetEnvCheckStatsQuery").msgclass
        GetEnvCheckStatsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("isuxportal.proto.services.admin.GetEnvCheckStatsResponse").msgclass
      end
    end
  end
end
