// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/common/me.proto (package isuxportal.proto.services.common, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_team } from "../../resources/team_pb";
import { file_isuxportal_resources_contestant } from "../../resources/contestant_pb";
import { file_isuxportal_resources_contestant_instance } from "../../resources/contestant_instance_pb";
import { file_isuxportal_resources_contest } from "../../resources/contest_pb";

/**
 * Describes the file isuxportal/services/common/me.proto.
 */
export const file_isuxportal_services_common_me = /*@__PURE__*/
  fileDesc("CiNpc3V4cG9ydGFsL3NlcnZpY2VzL2NvbW1vbi9tZS5wcm90bxIgaXN1eHBvcnRhbC5wcm90by5zZXJ2aWNlcy5jb21tb24iGgoYR2V0Q3VycmVudFNlc3Npb25SZXF1ZXN0Ir4CChlHZXRDdXJyZW50U2Vzc2lvblJlc3BvbnNlEi4KBHRlYW0YASABKAsyIC5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcy5UZWFtEjoKCmNvbnRlc3RhbnQYAiABKAsyJi5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcy5Db250ZXN0YW50EhkKEWRpc2NvcmRfc2VydmVyX2lkGAMgASgJEjQKB2NvbnRlc3QYBCABKAsyIy5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcy5Db250ZXN0EkwKFGNvbnRlc3RhbnRfaW5zdGFuY2VzGAUgAygLMi4uaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMuQ29udGVzdGFudEluc3RhbmNlEhYKDnB1c2hfdmFwaWRfa2V5GAYgASgJQqsCCiRjb20uaXN1eHBvcnRhbC5wcm90by5zZXJ2aWNlcy5jb21tb25CB01lUHJvdG9QAVpWZ2l0aHViLmNvbS9pc3Vjb24vaXN1Y29uMTQtcG9ydGFsL3N1cGVydmlzb3IvZHVtbXliZW5jaC9nZW4vaXN1eHBvcnRhbC9zZXJ2aWNlcy9jb21tb26iAgRJUFNDqgIgSXN1eHBvcnRhbC5Qcm90by5TZXJ2aWNlcy5Db21tb27KAiBJc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXENvbW1vbuICLElzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcQ29tbW9uXEdQQk1ldGFkYXRh6gIjSXN1eHBvcnRhbDo6UHJvdG86OlNlcnZpY2VzOjpDb21tb25iBnByb3RvMw", [file_isuxportal_resources_team, file_isuxportal_resources_contestant, file_isuxportal_resources_contestant_instance, file_isuxportal_resources_contest]);

/**
 * Describes the message isuxportal.proto.services.common.GetCurrentSessionRequest.
 * Use `create(GetCurrentSessionRequestSchema)` to create a new message.
 */
export const GetCurrentSessionRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_common_me, 0);

/**
 * Describes the message isuxportal.proto.services.common.GetCurrentSessionResponse.
 * Use `create(GetCurrentSessionResponseSchema)` to create a new message.
 */
export const GetCurrentSessionResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_common_me, 1);

