// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/common/storage.proto (package isuxportal.proto.services.common, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file isuxportal/services/common/storage.proto.
 */
export declare const file_isuxportal_services_common_storage: GenFile;

/**
 * @generated from message isuxportal.proto.services.common.GetAvatarUrlRequest
 */
export declare type GetAvatarUrlRequest = Message<"isuxportal.proto.services.common.GetAvatarUrlRequest"> & {
};

/**
 * Describes the message isuxportal.proto.services.common.GetAvatarUrlRequest.
 * Use `create(GetAvatarUrlRequestSchema)` to create a new message.
 */
export declare const GetAvatarUrlRequestSchema: GenMessage<GetAvatarUrlRequest>;

/**
 * @generated from message isuxportal.proto.services.common.GetAvatarUrlResponse
 */
export declare type GetAvatarUrlResponse = Message<"isuxportal.proto.services.common.GetAvatarUrlResponse"> & {
  /**
   * @generated from field: string upload_presigned = 1;
   */
  uploadPresigned: string;

  /**
   * @generated from field: string url = 2;
   */
  url: string;
};

/**
 * Describes the message isuxportal.proto.services.common.GetAvatarUrlResponse.
 * Use `create(GetAvatarUrlResponseSchema)` to create a new message.
 */
export declare const GetAvatarUrlResponseSchema: GenMessage<GetAvatarUrlResponse>;

