// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/common/storage.proto (package isuxportal.proto.services.common, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/services/common/storage.proto.
 */
export const file_isuxportal_services_common_storage = /*@__PURE__*/
  fileDesc("Cihpc3V4cG9ydGFsL3NlcnZpY2VzL2NvbW1vbi9zdG9yYWdlLnByb3RvEiBpc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLmNvbW1vbiIVChNHZXRBdmF0YXJVcmxSZXF1ZXN0Ij0KFEdldEF2YXRhclVybFJlc3BvbnNlEhgKEHVwbG9hZF9wcmVzaWduZWQYASABKAkSCwoDdXJsGAIgASgJQrACCiRjb20uaXN1eHBvcnRhbC5wcm90by5zZXJ2aWNlcy5jb21tb25CDFN0b3JhZ2VQcm90b1ABWlZnaXRodWIuY29tL2lzdWNvbi9pc3Vjb24xNC1wb3J0YWwvc3VwZXJ2aXNvci9kdW1teWJlbmNoL2dlbi9pc3V4cG9ydGFsL3NlcnZpY2VzL2NvbW1vbqICBElQU0OqAiBJc3V4cG9ydGFsLlByb3RvLlNlcnZpY2VzLkNvbW1vbsoCIElzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcQ29tbW9u4gIsSXN1eHBvcnRhbFxQcm90b1xTZXJ2aWNlc1xDb21tb25cR1BCTWV0YWRhdGHqAiNJc3V4cG9ydGFsOjpQcm90bzo6U2VydmljZXM6OkNvbW1vbmIGcHJvdG8z");

/**
 * Describes the message isuxportal.proto.services.common.GetAvatarUrlRequest.
 * Use `create(GetAvatarUrlRequestSchema)` to create a new message.
 */
export const GetAvatarUrlRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_common_storage, 0);

/**
 * Describes the message isuxportal.proto.services.common.GetAvatarUrlResponse.
 * Use `create(GetAvatarUrlResponseSchema)` to create a new message.
 */
export const GetAvatarUrlResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_common_storage, 1);

