// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/common/storage.proto (package isuxportal.proto.services.common, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/services/common/storage.proto.
 */
export const file_isuxportal_services_common_storage = /*@__PURE__*/
  fileDesc("Cihpc3V4cG9ydGFsL3NlcnZpY2VzL2NvbW1vbi9zdG9yYWdlLnByb3RvEiBpc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLmNvbW1vbiIVChNHZXRBdmF0YXJVcmxSZXF1ZXN0Ij0KFEdldEF2YXRhclVybFJlc3BvbnNlEhgKEHVwbG9hZF9wcmVzaWduZWQYASABKAkSCwoDdXJsGAIgASgJQp8CCiRjb20uaXN1eHBvcnRhbC5wcm90by5zZXJ2aWNlcy5jb21tb25CDFN0b3JhZ2VQcm90b1ABWkVnaXRodWIuY29tL2lzdWNvbi9pc3Vjb24xNC1wb3J0YWwvcHJvdG8uZ28vaXN1eHBvcnRhbC9zZXJ2aWNlcy9jb21tb26iAgRJUFNDqgIgSXN1eHBvcnRhbC5Qcm90by5TZXJ2aWNlcy5Db21tb27KAiBJc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXENvbW1vbuICLElzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcQ29tbW9uXEdQQk1ldGFkYXRh6gIjSXN1eHBvcnRhbDo6UHJvdG86OlNlcnZpY2VzOjpDb21tb25iBnByb3RvMw");

/**
 * Describes the message isuxportal.proto.services.common.GetAvatarUrlRequest.
 * Use `create(GetAvatarUrlRequestSchema)` to create a new message.
 */
export const GetAvatarUrlRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_common_storage, 0);

/**
 * Describes the message isuxportal.proto.services.common.GetAvatarUrlResponse.
 * Use `create(GetAvatarUrlResponseSchema)` to create a new message.
 */
export const GetAvatarUrlResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_common_storage, 1);

