// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/resources/clarification.proto (package isuxportal.proto.resources, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_team } from "./team_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file isuxportal/resources/clarification.proto.
 */
export const file_isuxportal_resources_clarification = /*@__PURE__*/
  fileDesc("Cihpc3V4cG9ydGFsL3Jlc291cmNlcy9jbGFyaWZpY2F0aW9uLnByb3RvEhppc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcyKuAgoNQ2xhcmlmaWNhdGlvbhIKCgJpZBgBIAEoAxIPCgd0ZWFtX2lkGAIgASgDEhAKCGFuc3dlcmVkGAMgASgIEhEKCWRpc2Nsb3NlZBgEIAEoCBIQCghxdWVzdGlvbhgFIAEoCRIOCgZhbnN3ZXIYBiABKAkSLgoKY3JlYXRlZF9hdBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLwoLYW5zd2VyZWRfYXQYCCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhkKEW9yaWdpbmFsX3F1ZXN0aW9uGAkgASgJEg0KBWFkbWluGAogASgIEi4KBHRlYW0YECABKAsyIC5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcy5UZWFtQv8BCh5jb20uaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXNCEkNsYXJpZmljYXRpb25Qcm90b1ABWj9naXRodWIuY29tL2lzdWNvbi9pc3Vjb24xNC1wb3J0YWwvcHJvdG8uZ28vaXN1eHBvcnRhbC9yZXNvdXJjZXOiAgNJUFKqAhpJc3V4cG9ydGFsLlByb3RvLlJlc291cmNlc8oCGklzdXhwb3J0YWxcUHJvdG9cUmVzb3VyY2Vz4gImSXN1eHBvcnRhbFxQcm90b1xSZXNvdXJjZXNcR1BCTWV0YWRhdGHqAhxJc3V4cG9ydGFsOjpQcm90bzo6UmVzb3VyY2VzYgZwcm90bzM", [file_isuxportal_resources_team, file_google_protobuf_timestamp]);

/**
 * Describes the message isuxportal.proto.resources.Clarification.
 * Use `create(ClarificationSchema)` to create a new message.
 */
export const ClarificationSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_clarification, 0);

