// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/resources/contestant_instance.proto (package isuxportal.proto.resources, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_team } from "./team_pb";

/**
 * Describes the file isuxportal/resources/contestant_instance.proto.
 */
export const file_isuxportal_resources_contestant_instance = /*@__PURE__*/
  fileDesc("Ci5pc3V4cG9ydGFsL3Jlc291cmNlcy9jb250ZXN0YW50X2luc3RhbmNlLnByb3RvEhppc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcyLiAgoSQ29udGVzdGFudEluc3RhbmNlEgoKAmlkGAcgASgDEhAKCGNsb3VkX2lkGAEgASgJEg8KB3RlYW1faWQYAiABKAMSDgoGbnVtYmVyGAMgASgDEhsKE3B1YmxpY19pcHY0X2FkZHJlc3MYBCABKAkSHAoUcHJpdmF0ZV9pcHY0X2FkZHJlc3MYBSABKAkSRQoGc3RhdHVzGAYgASgOMjUuaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMuQ29udGVzdGFudEluc3RhbmNlLlN0YXR1cxIuCgR0ZWFtGBAgASgLMiAuaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMuVGVhbSJbCgZTdGF0dXMSCwoHVU5LTk9XThAAEgsKB1BFTkRJTkcQARINCglNT0RJRllJTkcQAhILCgdTVE9QUEVEEAMSCwoHUlVOTklORxAEEg4KClRFUk1JTkFURUQQBUKVAgoeY29tLmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzQhdDb250ZXN0YW50SW5zdGFuY2VQcm90b1ABWlBnaXRodWIuY29tL2lzdWNvbi9pc3Vjb24xNC1wb3J0YWwvc3VwZXJ2aXNvci9kdW1teWJlbmNoL2dlbi9pc3V4cG9ydGFsL3Jlc291cmNlc6ICA0lQUqoCGklzdXhwb3J0YWwuUHJvdG8uUmVzb3VyY2VzygIaSXN1eHBvcnRhbFxQcm90b1xSZXNvdXJjZXPiAiZJc3V4cG9ydGFsXFByb3RvXFJlc291cmNlc1xHUEJNZXRhZGF0YeoCHElzdXhwb3J0YWw6OlByb3RvOjpSZXNvdXJjZXNiBnByb3RvMw", [file_isuxportal_resources_team]);

/**
 * Describes the message isuxportal.proto.resources.ContestantInstance.
 * Use `create(ContestantInstanceSchema)` to create a new message.
 */
export const ContestantInstanceSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_contestant_instance, 0);

/**
 * Describes the enum isuxportal.proto.resources.ContestantInstance.Status.
 */
export const ContestantInstance_StatusSchema = /*@__PURE__*/
  enumDesc(file_isuxportal_resources_contestant_instance, 0, 0);

/**
 * @generated from enum isuxportal.proto.resources.ContestantInstance.Status
 */
export const ContestantInstance_Status = /*@__PURE__*/
  tsEnum(ContestantInstance_StatusSchema);

