// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/resources/contest.proto (package isuxportal.proto.resources, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file isuxportal/resources/contest.proto.
 */
export const file_isuxportal_resources_contest = /*@__PURE__*/
  fileDesc("CiJpc3V4cG9ydGFsL3Jlc291cmNlcy9jb250ZXN0LnByb3RvEhppc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcyKcAwoHQ29udGVzdBI5ChVyZWdpc3RyYXRpb25fb3BlbnNfYXQYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjoKFnJlZ2lzdHJhdGlvbl9jbG9zZXNfYXQYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi0KCXN0YXJ0c19hdBgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKZnJlZXplc19hdBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASKwoHZW5kc19hdBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASOgoGc3RhdHVzGAYgASgOMiouaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMuQ29udGVzdC5TdGF0dXMSDgoGZnJvemVuGAcgASgIIkIKBlN0YXR1cxILCgdTVEFOREJZEAASEAoMUkVHSVNUUkFUSU9OEAESCwoHU1RBUlRFRBACEgwKCEZJTklTSEVEEANCigIKHmNvbS5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlc0IMQ29udGVzdFByb3RvUAFaUGdpdGh1Yi5jb20vaXN1Y29uL2lzdWNvbjE0LXBvcnRhbC9zdXBlcnZpc29yL2R1bW15YmVuY2gvZ2VuL2lzdXhwb3J0YWwvcmVzb3VyY2VzogIDSVBSqgIaSXN1eHBvcnRhbC5Qcm90by5SZXNvdXJjZXPKAhpJc3V4cG9ydGFsXFByb3RvXFJlc291cmNlc+ICJklzdXhwb3J0YWxcUHJvdG9cUmVzb3VyY2VzXEdQQk1ldGFkYXRh6gIcSXN1eHBvcnRhbDo6UHJvdG86OlJlc291cmNlc2IGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * Describes the message isuxportal.proto.resources.Contest.
 * Use `create(ContestSchema)` to create a new message.
 */
export const ContestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_contest, 0);

/**
 * Describes the enum isuxportal.proto.resources.Contest.Status.
 */
export const Contest_StatusSchema = /*@__PURE__*/
  enumDesc(file_isuxportal_resources_contest, 0, 0);

/**
 * @generated from enum isuxportal.proto.resources.Contest.Status
 */
export const Contest_Status = /*@__PURE__*/
  tsEnum(Contest_StatusSchema);

