// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/resources/contestant.proto (package isuxportal.proto.resources, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/resources/contestant.proto.
 */
export const file_isuxportal_resources_contestant = /*@__PURE__*/
  fileDesc("CiVpc3V4cG9ydGFsL3Jlc291cmNlcy9jb250ZXN0YW50LnByb3RvEhppc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcyLPAgoKQ29udGVzdGFudBIKCgJpZBgBIAEoAxIPCgd0ZWFtX2lkGAIgASgDEgwKBG5hbWUYAyABKAkSRwoGZGV0YWlsGAcgASgLMjcuaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMuQ29udGVzdGFudC5Db250ZXN0YW50RGV0YWlsGswBChBDb250ZXN0YW50RGV0YWlsEhQKDGdpdGh1Yl9sb2dpbhgBIAEoCRITCgtkaXNjb3JkX3RhZxgCIAEoCRISCgppc19zdHVkZW50GAMgASgIEhIKCmF2YXRhcl91cmwYBCABKAkSEQoJZ2l0aHViX2lkGBAgASgJEhIKCmRpc2NvcmRfaWQYESABKAkSHQoVaXNfc3NoX2tleV9yZWdpc3RlcmVkGBUgASgIEh8KF2lzX2Rpc2NvcmRfZ3VpbGRfbWVtYmVyGBYgASgIQvwBCh5jb20uaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXNCD0NvbnRlc3RhbnRQcm90b1ABWj9naXRodWIuY29tL2lzdWNvbi9pc3Vjb24xNC1wb3J0YWwvcHJvdG8uZ28vaXN1eHBvcnRhbC9yZXNvdXJjZXOiAgNJUFKqAhpJc3V4cG9ydGFsLlByb3RvLlJlc291cmNlc8oCGklzdXhwb3J0YWxcUHJvdG9cUmVzb3VyY2Vz4gImSXN1eHBvcnRhbFxQcm90b1xSZXNvdXJjZXNcR1BCTWV0YWRhdGHqAhxJc3V4cG9ydGFsOjpQcm90bzo6UmVzb3VyY2VzYgZwcm90bzM");

/**
 * Describes the message isuxportal.proto.resources.Contestant.
 * Use `create(ContestantSchema)` to create a new message.
 */
export const ContestantSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_contestant, 0);

/**
 * Describes the message isuxportal.proto.resources.Contestant.ContestantDetail.
 * Use `create(Contestant_ContestantDetailSchema)` to create a new message.
 */
export const Contestant_ContestantDetailSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_contestant, 0, 0);

