// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/resources/contestant.proto (package isuxportal.proto.resources, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file isuxportal/resources/contestant.proto.
 */
export declare const file_isuxportal_resources_contestant: GenFile;

/**
 * @generated from message isuxportal.proto.resources.Contestant
 */
export declare type Contestant = Message<"isuxportal.proto.resources.Contestant"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: int64 team_id = 2;
   */
  teamId: bigint;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: isuxportal.proto.resources.Contestant.ContestantDetail detail = 7;
   */
  detail?: Contestant_ContestantDetail;
};

/**
 * Describes the message isuxportal.proto.resources.Contestant.
 * Use `create(ContestantSchema)` to create a new message.
 */
export declare const ContestantSchema: GenMessage<Contestant>;

/**
 * @generated from message isuxportal.proto.resources.Contestant.ContestantDetail
 */
export declare type Contestant_ContestantDetail = Message<"isuxportal.proto.resources.Contestant.ContestantDetail"> & {
  /**
   * @generated from field: string github_login = 1;
   */
  githubLogin: string;

  /**
   * @generated from field: string discord_tag = 2;
   */
  discordTag: string;

  /**
   * @generated from field: bool is_student = 3;
   */
  isStudent: boolean;

  /**
   * @generated from field: string avatar_url = 4;
   */
  avatarUrl: string;

  /**
   * @generated from field: bool is_in_person = 5;
   */
  isInPerson: boolean;

  /**
   * @generated from field: string github_id = 16;
   */
  githubId: string;

  /**
   * @generated from field: string discord_id = 17;
   */
  discordId: string;

  /**
   * @generated from field: bool is_ssh_key_registered = 21;
   */
  isSshKeyRegistered: boolean;

  /**
   * @generated from field: bool is_discord_guild_member = 22;
   */
  isDiscordGuildMember: boolean;
};

/**
 * Describes the message isuxportal.proto.resources.Contestant.ContestantDetail.
 * Use `create(Contestant_ContestantDetailSchema)` to create a new message.
 */
export declare const Contestant_ContestantDetailSchema: GenMessage<Contestant_ContestantDetail>;

