// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/resources/coupon.proto (package isuxportal.proto.resources, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/resources/coupon.proto.
 */
export const file_isuxportal_resources_coupon = /*@__PURE__*/
  fileDesc("CiFpc3V4cG9ydGFsL3Jlc291cmNlcy9jb3Vwb24ucHJvdG8SGmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzIkUKBkNvdXBvbhIKCgJpZBgBIAEoAxIPCgd0ZWFtX2lkGAIgASgDEgwKBGNvZGUYAyADKAkSEAoIYWN0aXZhdGUYBCABKAhC+AEKHmNvbS5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlc0ILQ291cG9uUHJvdG9QAVo/Z2l0aHViLmNvbS9pc3Vjb24vaXN1Y29uMTQtcG9ydGFsL3Byb3RvLmdvL2lzdXhwb3J0YWwvcmVzb3VyY2VzogIDSVBSqgIaSXN1eHBvcnRhbC5Qcm90by5SZXNvdXJjZXPKAhpJc3V4cG9ydGFsXFByb3RvXFJlc291cmNlc+ICJklzdXhwb3J0YWxcUHJvdG9cUmVzb3VyY2VzXEdQQk1ldGFkYXRh6gIcSXN1eHBvcnRhbDo6UHJvdG86OlJlc291cmNlc2IGcHJvdG8z");

/**
 * Describes the message isuxportal.proto.resources.Coupon.
 * Use `create(CouponSchema)` to create a new message.
 */
export const CouponSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_coupon, 0);

