// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/resources/env_check.proto (package isuxportal.proto.resources, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file isuxportal/resources/env_check.proto.
 */
export const file_isuxportal_resources_env_check = /*@__PURE__*/
  fileDesc("CiRpc3V4cG9ydGFsL3Jlc291cmNlcy9lbnZfY2hlY2sucHJvdG8SGmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzIvMBCghFbnZDaGVjaxIKCgJpZBgBIAEoAxIPCgd0ZWFtX2lkGAIgASgDEgwKBG5hbWUYAyABKAkSEgoKaXBfYWRkcmVzcxgEIAEoCRIOCgZwYXNzZWQYBSABKAgSDwoHbWVzc2FnZRgGIAEoCRIVCg1hZG1pbl9tZXNzYWdlGAcgASgJEhAKCHJhd19kYXRhGAggASgJEi4KCmNyZWF0ZWRfYXQYCSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYCiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wKlAKDkVudkNoZWNrU3RhdHVzEg0KCVBSRVBBUklORxAAEg8KC05PVF9TVEFSVEVEEAESFAoQQ1JFQVRFRF9JTlNUQU5DRRACEggKBERPTkUQA0KLAgoeY29tLmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzQg1FbnZDaGVja1Byb3RvUAFaUGdpdGh1Yi5jb20vaXN1Y29uL2lzdWNvbjE0LXBvcnRhbC9zdXBlcnZpc29yL2R1bW15YmVuY2gvZ2VuL2lzdXhwb3J0YWwvcmVzb3VyY2VzogIDSVBSqgIaSXN1eHBvcnRhbC5Qcm90by5SZXNvdXJjZXPKAhpJc3V4cG9ydGFsXFByb3RvXFJlc291cmNlc+ICJklzdXhwb3J0YWxcUHJvdG9cUmVzb3VyY2VzXEdQQk1ldGFkYXRh6gIcSXN1eHBvcnRhbDo6UHJvdG86OlJlc291cmNlc2IGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * Describes the message isuxportal.proto.resources.EnvCheck.
 * Use `create(EnvCheckSchema)` to create a new message.
 */
export const EnvCheckSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_env_check, 0);

/**
 * Describes the enum isuxportal.proto.resources.EnvCheckStatus.
 */
export const EnvCheckStatusSchema = /*@__PURE__*/
  enumDesc(file_isuxportal_resources_env_check, 0);

/**
 * @generated from enum isuxportal.proto.resources.EnvCheckStatus
 */
export const EnvCheckStatus = /*@__PURE__*/
  tsEnum(EnvCheckStatusSchema);

