// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/resources/instance_command_execute_request.proto (package isuxportal.proto.resources, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_contestant_instance } from "./contestant_instance_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file isuxportal/resources/instance_command_execute_request.proto.
 */
export const file_isuxportal_resources_instance_command_execute_request = /*@__PURE__*/
  fileDesc("Cjtpc3V4cG9ydGFsL3Jlc291cmNlcy9pbnN0YW5jZV9jb21tYW5kX2V4ZWN1dGVfcmVxdWVzdC5wcm90bxIaaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMipgEKHUluc3RhbmNlQ29tbWFuZEV4ZWN1dGVSZXF1ZXN0EgoKAmlkGAEgASgDEg8KB2NvbW1hbmQYAiABKAkSLgoKY3JlYXRlZF9hdBgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASGgoSdG90YWxfdGFyZ2V0X2NvdW50GAQgASgDEhwKFHRvdGFsX2ZpbmlzaGVkX2NvdW50GAUgASgDIrUBCiNJbnN0YW5jZUNvbW1hbmRFeGVjdXRlUmVxdWVzdFJlc3VsdBIKCgJpZBgBIAEoAxI+CgZ0YXJnZXQYAiABKAsyLi5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcy5Db250ZXN0YW50SW5zdGFuY2USEQoJZXhpdF9jb2RlGAMgASgFEi8KC2ZpbmlzaGVkX2F0GAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEKgAgoeY29tLmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzQiJJbnN0YW5jZUNvbW1hbmRFeGVjdXRlUmVxdWVzdFByb3RvUAFaUGdpdGh1Yi5jb20vaXN1Y29uL2lzdWNvbjE0LXBvcnRhbC9zdXBlcnZpc29yL2R1bW15YmVuY2gvZ2VuL2lzdXhwb3J0YWwvcmVzb3VyY2VzogIDSVBSqgIaSXN1eHBvcnRhbC5Qcm90by5SZXNvdXJjZXPKAhpJc3V4cG9ydGFsXFByb3RvXFJlc291cmNlc+ICJklzdXhwb3J0YWxcUHJvdG9cUmVzb3VyY2VzXEdQQk1ldGFkYXRh6gIcSXN1eHBvcnRhbDo6UHJvdG86OlJlc291cmNlc2IGcHJvdG8z", [file_isuxportal_resources_contestant_instance, file_google_protobuf_timestamp]);

/**
 * Describes the message isuxportal.proto.resources.InstanceCommandExecuteRequest.
 * Use `create(InstanceCommandExecuteRequestSchema)` to create a new message.
 */
export const InstanceCommandExecuteRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_instance_command_execute_request, 0);

/**
 * Describes the message isuxportal.proto.resources.InstanceCommandExecuteRequestResult.
 * Use `create(InstanceCommandExecuteRequestResultSchema)` to create a new message.
 */
export const InstanceCommandExecuteRequestResultSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_instance_command_execute_request, 1);

