// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/resources/instance_command_execute_request.proto (package isuxportal.proto.resources, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_contestant_instance } from "./contestant_instance_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file isuxportal/resources/instance_command_execute_request.proto.
 */
export const file_isuxportal_resources_instance_command_execute_request = /*@__PURE__*/
  fileDesc("Cjtpc3V4cG9ydGFsL3Jlc291cmNlcy9pbnN0YW5jZV9jb21tYW5kX2V4ZWN1dGVfcmVxdWVzdC5wcm90bxIaaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMipgEKHUluc3RhbmNlQ29tbWFuZEV4ZWN1dGVSZXF1ZXN0EgoKAmlkGAEgASgDEg8KB2NvbW1hbmQYAiABKAkSLgoKY3JlYXRlZF9hdBgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASGgoSdG90YWxfdGFyZ2V0X2NvdW50GAQgASgDEhwKFHRvdGFsX2ZpbmlzaGVkX2NvdW50GAUgASgDIrkBCiNJbnN0YW5jZUNvbW1hbmRFeGVjdXRlUmVxdWVzdFJlc3VsdBI+CgZ0YXJnZXQYASABKAsyLi5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcy5Db250ZXN0YW50SW5zdGFuY2USDgoGb3V0cHV0GAIgASgJEhEKCWV4aXRfY29kZRgDIAEoBRIvCgtmaW5pc2hlZF9hdBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCoAIKHmNvbS5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlc0IiSW5zdGFuY2VDb21tYW5kRXhlY3V0ZVJlcXVlc3RQcm90b1ABWlBnaXRodWIuY29tL2lzdWNvbi9pc3Vjb24xNC1wb3J0YWwvc3VwZXJ2aXNvci9kdW1teWJlbmNoL2dlbi9pc3V4cG9ydGFsL3Jlc291cmNlc6ICA0lQUqoCGklzdXhwb3J0YWwuUHJvdG8uUmVzb3VyY2VzygIaSXN1eHBvcnRhbFxQcm90b1xSZXNvdXJjZXPiAiZJc3V4cG9ydGFsXFByb3RvXFJlc291cmNlc1xHUEJNZXRhZGF0YeoCHElzdXhwb3J0YWw6OlByb3RvOjpSZXNvdXJjZXNiBnByb3RvMw", [file_isuxportal_resources_contestant_instance, file_google_protobuf_timestamp]);

/**
 * Describes the message isuxportal.proto.resources.InstanceCommandExecuteRequest.
 * Use `create(InstanceCommandExecuteRequestSchema)` to create a new message.
 */
export const InstanceCommandExecuteRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_instance_command_execute_request, 0);

/**
 * Describes the message isuxportal.proto.resources.InstanceCommandExecuteRequestResult.
 * Use `create(InstanceCommandExecuteRequestResultSchema)` to create a new message.
 */
export const InstanceCommandExecuteRequestResultSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_instance_command_execute_request, 1);

