// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/resources/notification.proto (package isuxportal.proto.resources, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file isuxportal/resources/notification.proto.
 */
export const file_isuxportal_resources_notification = /*@__PURE__*/
  fileDesc("Cidpc3V4cG9ydGFsL3Jlc291cmNlcy9ub3RpZmljYXRpb24ucHJvdG8SGmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzIpYECgxOb3RpZmljYXRpb24SCgoCaWQYASABKAMSLgoKY3JlYXRlZF9hdBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASXQoVY29udGVudF9iZW5jaG1hcmtfam9iGAMgASgLMjwuaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMuTm90aWZpY2F0aW9uLkJlbmNobWFya0pvYk1lc3NhZ2VIABJeChVjb250ZW50X2NsYXJpZmljYXRpb24YBCABKAsyPS5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcy5Ob3RpZmljYXRpb24uQ2xhcmlmaWNhdGlvbk1lc3NhZ2VIABJMCgxjb250ZW50X3Rlc3QYBSABKAsyNC5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcy5Ob3RpZmljYXRpb24uVGVzdE1lc3NhZ2VIABovChNCZW5jaG1hcmtKb2JNZXNzYWdlEhgKEGJlbmNobWFya19qb2JfaWQYASABKAMaXwoUQ2xhcmlmaWNhdGlvbk1lc3NhZ2USGAoQY2xhcmlmaWNhdGlvbl9pZBgBIAEoAxINCgVvd25lZBgCIAEoCBIPCgd1cGRhdGVkGAMgASgIEg0KBWFkbWluGAQgASgIGiAKC1Rlc3RNZXNzYWdlEhEKCXNvbWV0aGluZxgBIAEoA0IJCgdjb250ZW50Qv4BCh5jb20uaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXNCEU5vdGlmaWNhdGlvblByb3RvUAFaP2dpdGh1Yi5jb20vaXN1Y29uL2lzdWNvbjE0LXBvcnRhbC9wcm90by5nby9pc3V4cG9ydGFsL3Jlc291cmNlc6ICA0lQUqoCGklzdXhwb3J0YWwuUHJvdG8uUmVzb3VyY2VzygIaSXN1eHBvcnRhbFxQcm90b1xSZXNvdXJjZXPiAiZJc3V4cG9ydGFsXFByb3RvXFJlc291cmNlc1xHUEJNZXRhZGF0YeoCHElzdXhwb3J0YWw6OlByb3RvOjpSZXNvdXJjZXNiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * Describes the message isuxportal.proto.resources.Notification.
 * Use `create(NotificationSchema)` to create a new message.
 */
export const NotificationSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_notification, 0);

/**
 * Describes the message isuxportal.proto.resources.Notification.BenchmarkJobMessage.
 * Use `create(Notification_BenchmarkJobMessageSchema)` to create a new message.
 */
export const Notification_BenchmarkJobMessageSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_notification, 0, 0);

/**
 * Describes the message isuxportal.proto.resources.Notification.ClarificationMessage.
 * Use `create(Notification_ClarificationMessageSchema)` to create a new message.
 */
export const Notification_ClarificationMessageSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_notification, 0, 1);

/**
 * Describes the message isuxportal.proto.resources.Notification.TestMessage.
 * Use `create(Notification_TestMessageSchema)` to create a new message.
 */
export const Notification_TestMessageSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_notification, 0, 2);

