// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/resources/staff.proto (package isuxportal.proto.resources, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/resources/staff.proto.
 */
export const file_isuxportal_resources_staff = /*@__PURE__*/
  fileDesc("CiBpc3V4cG9ydGFsL3Jlc291cmNlcy9zdGFmZi5wcm90bxIaaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMiKQoFU3RhZmYSCgoCaWQYASABKAMSFAoMZ2l0aHViX2xvZ2luGAIgASgJQogCCh5jb20uaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXNCClN0YWZmUHJvdG9QAVpQZ2l0aHViLmNvbS9pc3Vjb24vaXN1Y29uMTQtcG9ydGFsL3N1cGVydmlzb3IvZHVtbXliZW5jaC9nZW4vaXN1eHBvcnRhbC9yZXNvdXJjZXOiAgNJUFKqAhpJc3V4cG9ydGFsLlByb3RvLlJlc291cmNlc8oCGklzdXhwb3J0YWxcUHJvdG9cUmVzb3VyY2Vz4gImSXN1eHBvcnRhbFxQcm90b1xSZXNvdXJjZXNcR1BCTWV0YWRhdGHqAhxJc3V4cG9ydGFsOjpQcm90bzo6UmVzb3VyY2VzYgZwcm90bzM");

/**
 * Describes the message isuxportal.proto.resources.Staff.
 * Use `create(StaffSchema)` to create a new message.
 */
export const StaffSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_staff, 0);

