// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/resources/staff.proto (package isuxportal.proto.resources, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/resources/staff.proto.
 */
export const file_isuxportal_resources_staff = /*@__PURE__*/
  fileDesc("CiBpc3V4cG9ydGFsL3Jlc291cmNlcy9zdGFmZi5wcm90bxIaaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMiKQoFU3RhZmYSCgoCaWQYASABKAMSFAoMZ2l0aHViX2xvZ2luGAIgASgJQvcBCh5jb20uaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXNCClN0YWZmUHJvdG9QAVo/Z2l0aHViLmNvbS9pc3Vjb24vaXN1Y29uMTQtcG9ydGFsL3Byb3RvLmdvL2lzdXhwb3J0YWwvcmVzb3VyY2VzogIDSVBSqgIaSXN1eHBvcnRhbC5Qcm90by5SZXNvdXJjZXPKAhpJc3V4cG9ydGFsXFByb3RvXFJlc291cmNlc+ICJklzdXhwb3J0YWxcUHJvdG9cUmVzb3VyY2VzXEdQQk1ldGFkYXRh6gIcSXN1eHBvcnRhbDo6UHJvdG86OlJlc291cmNlc2IGcHJvdG8z");

/**
 * Describes the message isuxportal.proto.resources.Staff.
 * Use `create(StaffSchema)` to create a new message.
 */
export const StaffSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_staff, 0);

