// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/resources/staff.proto (package isuxportal.proto.resources, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file isuxportal/resources/staff.proto.
 */
export declare const file_isuxportal_resources_staff: GenFile;

/**
 * @generated from message isuxportal.proto.resources.Staff
 */
export declare type Staff = Message<"isuxportal.proto.resources.Staff"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string github_login = 2;
   */
  githubLogin: string;
};

/**
 * Describes the message isuxportal.proto.resources.Staff.
 * Use `create(StaffSchema)` to create a new message.
 */
export declare const StaffSchema: GenMessage<Staff>;

