// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/resources/survey_response.proto (package isuxportal.proto.resources, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/resources/survey_response.proto.
 */
export const file_isuxportal_resources_survey_response = /*@__PURE__*/
  fileDesc("Cippc3V4cG9ydGFsL3Jlc291cmNlcy9zdXJ2ZXlfcmVzcG9uc2UucHJvdG8SGmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzIiIKDlN1cnZleVJlc3BvbnNlEhAKCGxhbmd1YWdlGAEgASgJQpECCh5jb20uaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXNCE1N1cnZleVJlc3BvbnNlUHJvdG9QAVpQZ2l0aHViLmNvbS9pc3Vjb24vaXN1Y29uMTQtcG9ydGFsL3N1cGVydmlzb3IvZHVtbXliZW5jaC9nZW4vaXN1eHBvcnRhbC9yZXNvdXJjZXOiAgNJUFKqAhpJc3V4cG9ydGFsLlByb3RvLlJlc291cmNlc8oCGklzdXhwb3J0YWxcUHJvdG9cUmVzb3VyY2Vz4gImSXN1eHBvcnRhbFxQcm90b1xSZXNvdXJjZXNcR1BCTWV0YWRhdGHqAhxJc3V4cG9ydGFsOjpQcm90bzo6UmVzb3VyY2VzYgZwcm90bzM");

/**
 * Describes the message isuxportal.proto.resources.SurveyResponse.
 * Use `create(SurveyResponseSchema)` to create a new message.
 */
export const SurveyResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_survey_response, 0);

