// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/resources/survey_response.proto (package isuxportal.proto.resources, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/resources/survey_response.proto.
 */
export const file_isuxportal_resources_survey_response = /*@__PURE__*/
  fileDesc("Cippc3V4cG9ydGFsL3Jlc291cmNlcy9zdXJ2ZXlfcmVzcG9uc2UucHJvdG8SGmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzIiIKDlN1cnZleVJlc3BvbnNlEhAKCGxhbmd1YWdlGAEgASgJQoACCh5jb20uaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXNCE1N1cnZleVJlc3BvbnNlUHJvdG9QAVo/Z2l0aHViLmNvbS9pc3Vjb24vaXN1Y29uMTQtcG9ydGFsL3Byb3RvLmdvL2lzdXhwb3J0YWwvcmVzb3VyY2VzogIDSVBSqgIaSXN1eHBvcnRhbC5Qcm90by5SZXNvdXJjZXPKAhpJc3V4cG9ydGFsXFByb3RvXFJlc291cmNlc+ICJklzdXhwb3J0YWxcUHJvdG9cUmVzb3VyY2VzXEdQQk1ldGFkYXRh6gIcSXN1eHBvcnRhbDo6UHJvdG86OlJlc291cmNlc2IGcHJvdG8z");

/**
 * Describes the message isuxportal.proto.resources.SurveyResponse.
 * Use `create(SurveyResponseSchema)` to create a new message.
 */
export const SurveyResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_survey_response, 0);

