// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/resources/survey_response.proto (package isuxportal.proto.resources, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file isuxportal/resources/survey_response.proto.
 */
export declare const file_isuxportal_resources_survey_response: GenFile;

/**
 * @generated from message isuxportal.proto.resources.SurveyResponse
 */
export declare type SurveyResponse = Message<"isuxportal.proto.resources.SurveyResponse"> & {
  /**
   * @generated from field: string language = 1;
   */
  language: string;
};

/**
 * Describes the message isuxportal.proto.resources.SurveyResponse.
 * Use `create(SurveyResponseSchema)` to create a new message.
 */
export declare const SurveyResponseSchema: GenMessage<SurveyResponse>;

