// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/resources/team.proto (package isuxportal.proto.resources, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_contestant } from "./contestant_pb";

/**
 * Describes the file isuxportal/resources/team.proto.
 */
export const file_isuxportal_resources_team = /*@__PURE__*/
  fileDesc("Ch9pc3V4cG9ydGFsL3Jlc291cmNlcy90ZWFtLnByb3RvEhppc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcyLoAwoEVGVhbRIKCgJpZBgBIAEoAxIMCgRuYW1lGAIgASgJEhEKCWxlYWRlcl9pZBgDIAEoAxISCgptZW1iZXJfaWRzGAQgAygDEhsKE2ZpbmFsX3BhcnRpY2lwYXRpb24YBSABKAgSDgoGaGlkZGVuGAYgASgIEhEKCXdpdGhkcmF3bhgHIAEoCBIUCgxkaXNxdWFsaWZpZWQYCSABKAgSPwoHc3R1ZGVudBgKIAEoCzIuLmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzLlRlYW0uU3R1ZGVudFN0YXR1cxI7CgZkZXRhaWwYCCABKAsyKy5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcy5UZWFtLlRlYW1EZXRhaWwSNgoGbGVhZGVyGBAgASgLMiYuaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMuQ29udGVzdGFudBI3CgdtZW1iZXJzGBEgAygLMiYuaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMuQ29udGVzdGFudBofCg1TdHVkZW50U3RhdHVzEg4KBnN0YXR1cxgBIAEoCBo5CgpUZWFtRGV0YWlsEhUKDWVtYWlsX2FkZHJlc3MYASABKAkSFAoMaW52aXRlX3Rva2VuGBAgASgJQvYBCh5jb20uaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXNCCVRlYW1Qcm90b1ABWj9naXRodWIuY29tL2lzdWNvbi9pc3Vjb24xNC1wb3J0YWwvcHJvdG8uZ28vaXN1eHBvcnRhbC9yZXNvdXJjZXOiAgNJUFKqAhpJc3V4cG9ydGFsLlByb3RvLlJlc291cmNlc8oCGklzdXhwb3J0YWxcUHJvdG9cUmVzb3VyY2Vz4gImSXN1eHBvcnRhbFxQcm90b1xSZXNvdXJjZXNcR1BCTWV0YWRhdGHqAhxJc3V4cG9ydGFsOjpQcm90bzo6UmVzb3VyY2VzYgZwcm90bzM", [file_isuxportal_resources_contestant]);

/**
 * Describes the message isuxportal.proto.resources.Team.
 * Use `create(TeamSchema)` to create a new message.
 */
export const TeamSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_team, 0);

/**
 * Describes the message isuxportal.proto.resources.Team.StudentStatus.
 * Use `create(Team_StudentStatusSchema)` to create a new message.
 */
export const Team_StudentStatusSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_team, 0, 0);

/**
 * Describes the message isuxportal.proto.resources.Team.TeamDetail.
 * Use `create(Team_TeamDetailSchema)` to create a new message.
 */
export const Team_TeamDetailSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_resources_team, 0, 1);

