// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/registration/activate_coupon.proto (package isuxportal.proto.services.registration, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/services/registration/activate_coupon.proto.
 */
export const file_isuxportal_services_registration_activate_coupon = /*@__PURE__*/
  fileDesc("CjZpc3V4cG9ydGFsL3NlcnZpY2VzL3JlZ2lzdHJhdGlvbi9hY3RpdmF0ZV9jb3Vwb24ucHJvdG8SJmlzdXhwb3J0YWwucHJvdG8uc2VydmljZXMucmVnaXN0cmF0aW9uIigKFUFjdGl2YXRlQ291cG9uUmVxdWVzdBIPCgd0ZWFtX2lkGAEgASgDIhgKFkFjdGl2YXRlQ291cG9uUmVzcG9uc2VC2wIKKmNvbS5pc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLnJlZ2lzdHJhdGlvbkITQWN0aXZhdGVDb3Vwb25Qcm90b1ABWlxnaXRodWIuY29tL2lzdWNvbi9pc3Vjb24xNC1wb3J0YWwvc3VwZXJ2aXNvci9kdW1teWJlbmNoL2dlbi9pc3V4cG9ydGFsL3NlcnZpY2VzL3JlZ2lzdHJhdGlvbqICBElQU1KqAiZJc3V4cG9ydGFsLlByb3RvLlNlcnZpY2VzLlJlZ2lzdHJhdGlvbsoCJklzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcUmVnaXN0cmF0aW9u4gIySXN1eHBvcnRhbFxQcm90b1xTZXJ2aWNlc1xSZWdpc3RyYXRpb25cR1BCTWV0YWRhdGHqAilJc3V4cG9ydGFsOjpQcm90bzo6U2VydmljZXM6OlJlZ2lzdHJhdGlvbmIGcHJvdG8z");

/**
 * Describes the message isuxportal.proto.services.registration.ActivateCouponRequest.
 * Use `create(ActivateCouponRequestSchema)` to create a new message.
 */
export const ActivateCouponRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_activate_coupon, 0);

/**
 * Describes the message isuxportal.proto.services.registration.ActivateCouponResponse.
 * Use `create(ActivateCouponResponseSchema)` to create a new message.
 */
export const ActivateCouponResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_activate_coupon, 1);

