// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/registration/activate_coupon.proto (package isuxportal.proto.services.registration, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/services/registration/activate_coupon.proto.
 */
export const file_isuxportal_services_registration_activate_coupon = /*@__PURE__*/
  fileDesc("CjZpc3V4cG9ydGFsL3NlcnZpY2VzL3JlZ2lzdHJhdGlvbi9hY3RpdmF0ZV9jb3Vwb24ucHJvdG8SJmlzdXhwb3J0YWwucHJvdG8uc2VydmljZXMucmVnaXN0cmF0aW9uIigKFUFjdGl2YXRlQ291cG9uUmVxdWVzdBIPCgd0ZWFtX2lkGAEgASgDIhgKFkFjdGl2YXRlQ291cG9uUmVzcG9uc2VCygIKKmNvbS5pc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLnJlZ2lzdHJhdGlvbkITQWN0aXZhdGVDb3Vwb25Qcm90b1ABWktnaXRodWIuY29tL2lzdWNvbi9pc3Vjb24xNC1wb3J0YWwvcHJvdG8uZ28vaXN1eHBvcnRhbC9zZXJ2aWNlcy9yZWdpc3RyYXRpb26iAgRJUFNSqgImSXN1eHBvcnRhbC5Qcm90by5TZXJ2aWNlcy5SZWdpc3RyYXRpb27KAiZJc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXFJlZ2lzdHJhdGlvbuICMklzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcUmVnaXN0cmF0aW9uXEdQQk1ldGFkYXRh6gIpSXN1eHBvcnRhbDo6UHJvdG86OlNlcnZpY2VzOjpSZWdpc3RyYXRpb25iBnByb3RvMw");

/**
 * Describes the message isuxportal.proto.services.registration.ActivateCouponRequest.
 * Use `create(ActivateCouponRequestSchema)` to create a new message.
 */
export const ActivateCouponRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_activate_coupon, 0);

/**
 * Describes the message isuxportal.proto.services.registration.ActivateCouponResponse.
 * Use `create(ActivateCouponResponseSchema)` to create a new message.
 */
export const ActivateCouponResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_activate_coupon, 1);

