// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/registration/create_team.proto (package isuxportal.proto.services.registration, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/services/registration/create_team.proto.
 */
export const file_isuxportal_services_registration_create_team = /*@__PURE__*/
  fileDesc("CjJpc3V4cG9ydGFsL3NlcnZpY2VzL3JlZ2lzdHJhdGlvbi9jcmVhdGVfdGVhbS5wcm90bxImaXN1eHBvcnRhbC5wcm90by5zZXJ2aWNlcy5yZWdpc3RyYXRpb24ihQEKEUNyZWF0ZVRlYW1SZXF1ZXN0EhEKCXRlYW1fbmFtZRgBIAEoCRIMCgRuYW1lGAIgASgJEhUKDWVtYWlsX2FkZHJlc3MYAyABKAkSEgoKaXNfc3R1ZGVudBgEIAEoCBIUCgxpc19pbl9wZXJzb24YBSABKAgSDgoGaGlkZGVuGBAgASgIIiUKEkNyZWF0ZVRlYW1SZXNwb25zZRIPCgd0ZWFtX2lkGAEgASgDQsYCCipjb20uaXN1eHBvcnRhbC5wcm90by5zZXJ2aWNlcy5yZWdpc3RyYXRpb25CD0NyZWF0ZVRlYW1Qcm90b1ABWktnaXRodWIuY29tL2lzdWNvbi9pc3Vjb24xNC1wb3J0YWwvcHJvdG8uZ28vaXN1eHBvcnRhbC9zZXJ2aWNlcy9yZWdpc3RyYXRpb26iAgRJUFNSqgImSXN1eHBvcnRhbC5Qcm90by5TZXJ2aWNlcy5SZWdpc3RyYXRpb27KAiZJc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXFJlZ2lzdHJhdGlvbuICMklzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcUmVnaXN0cmF0aW9uXEdQQk1ldGFkYXRh6gIpSXN1eHBvcnRhbDo6UHJvdG86OlNlcnZpY2VzOjpSZWdpc3RyYXRpb25iBnByb3RvMw");

/**
 * Describes the message isuxportal.proto.services.registration.CreateTeamRequest.
 * Use `create(CreateTeamRequestSchema)` to create a new message.
 */
export const CreateTeamRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_create_team, 0);

/**
 * Describes the message isuxportal.proto.services.registration.CreateTeamResponse.
 * Use `create(CreateTeamResponseSchema)` to create a new message.
 */
export const CreateTeamResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_create_team, 1);

