// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/registration/create_team.proto (package isuxportal.proto.services.registration, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/services/registration/create_team.proto.
 */
export const file_isuxportal_services_registration_create_team = /*@__PURE__*/
  fileDesc("CjJpc3V4cG9ydGFsL3NlcnZpY2VzL3JlZ2lzdHJhdGlvbi9jcmVhdGVfdGVhbS5wcm90bxImaXN1eHBvcnRhbC5wcm90by5zZXJ2aWNlcy5yZWdpc3RyYXRpb24imQEKEUNyZWF0ZVRlYW1SZXF1ZXN0EhEKCXRlYW1fbmFtZRgBIAEoCRIMCgRuYW1lGAIgASgJEhUKDWVtYWlsX2FkZHJlc3MYAyABKAkSEgoKaXNfc3R1ZGVudBgEIAEoCBIUCgxpc19pbl9wZXJzb24YBSABKAgSEgoKYXZhdGFyX3VybBgGIAEoCRIOCgZoaWRkZW4YECABKAgiJQoSQ3JlYXRlVGVhbVJlc3BvbnNlEg8KB3RlYW1faWQYASABKANC1wIKKmNvbS5pc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLnJlZ2lzdHJhdGlvbkIPQ3JlYXRlVGVhbVByb3RvUAFaXGdpdGh1Yi5jb20vaXN1Y29uL2lzdWNvbjE0LXBvcnRhbC9zdXBlcnZpc29yL2R1bW15YmVuY2gvZ2VuL2lzdXhwb3J0YWwvc2VydmljZXMvcmVnaXN0cmF0aW9uogIESVBTUqoCJklzdXhwb3J0YWwuUHJvdG8uU2VydmljZXMuUmVnaXN0cmF0aW9uygImSXN1eHBvcnRhbFxQcm90b1xTZXJ2aWNlc1xSZWdpc3RyYXRpb27iAjJJc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXFJlZ2lzdHJhdGlvblxHUEJNZXRhZGF0YeoCKUlzdXhwb3J0YWw6OlByb3RvOjpTZXJ2aWNlczo6UmVnaXN0cmF0aW9uYgZwcm90bzM");

/**
 * Describes the message isuxportal.proto.services.registration.CreateTeamRequest.
 * Use `create(CreateTeamRequestSchema)` to create a new message.
 */
export const CreateTeamRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_create_team, 0);

/**
 * Describes the message isuxportal.proto.services.registration.CreateTeamResponse.
 * Use `create(CreateTeamResponseSchema)` to create a new message.
 */
export const CreateTeamResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_create_team, 1);

