// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/registration/create_team.proto (package isuxportal.proto.services.registration, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file isuxportal/services/registration/create_team.proto.
 */
export declare const file_isuxportal_services_registration_create_team: GenFile;

/**
 * @generated from message isuxportal.proto.services.registration.CreateTeamRequest
 */
export declare type CreateTeamRequest = Message<"isuxportal.proto.services.registration.CreateTeamRequest"> & {
  /**
   * @generated from field: string team_name = 1;
   */
  teamName: string;

  /**
   * contestant name
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string email_address = 3;
   */
  emailAddress: string;

  /**
   * @generated from field: bool is_student = 4;
   */
  isStudent: boolean;

  /**
   * @generated from field: bool is_in_person = 5;
   */
  isInPerson: boolean;

  /**
   * requires bypass token
   *
   * @generated from field: bool hidden = 16;
   */
  hidden: boolean;
};

/**
 * Describes the message isuxportal.proto.services.registration.CreateTeamRequest.
 * Use `create(CreateTeamRequestSchema)` to create a new message.
 */
export declare const CreateTeamRequestSchema: GenMessage<CreateTeamRequest>;

/**
 * @generated from message isuxportal.proto.services.registration.CreateTeamResponse
 */
export declare type CreateTeamResponse = Message<"isuxportal.proto.services.registration.CreateTeamResponse"> & {
  /**
   * @generated from field: int64 team_id = 1;
   */
  teamId: bigint;
};

/**
 * Describes the message isuxportal.proto.services.registration.CreateTeamResponse.
 * Use `create(CreateTeamResponseSchema)` to create a new message.
 */
export declare const CreateTeamResponseSchema: GenMessage<CreateTeamResponse>;

