// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/registration/env_check.proto (package isuxportal.proto.services.registration, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_env_check } from "../../resources/env_check_pb";

/**
 * Describes the file isuxportal/services/registration/env_check.proto.
 */
export const file_isuxportal_services_registration_env_check = /*@__PURE__*/
  fileDesc("CjBpc3V4cG9ydGFsL3NlcnZpY2VzL3JlZ2lzdHJhdGlvbi9lbnZfY2hlY2sucHJvdG8SJmlzdXhwb3J0YWwucHJvdG8uc2VydmljZXMucmVnaXN0cmF0aW9uIoMBCh5HZXRFbnZDaGVja0luZm9ybWF0aW9uUmVzcG9uc2USEAoIdGVtcGxhdGUYASABKAkSOgoGc3RhdHVzGAIgASgOMiouaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMuRW52Q2hlY2tTdGF0dXMSEwoLaW5zdGFuY2VfaXAYAyABKAlCxAIKKmNvbS5pc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLnJlZ2lzdHJhdGlvbkINRW52Q2hlY2tQcm90b1ABWktnaXRodWIuY29tL2lzdWNvbi9pc3Vjb24xNC1wb3J0YWwvcHJvdG8uZ28vaXN1eHBvcnRhbC9zZXJ2aWNlcy9yZWdpc3RyYXRpb26iAgRJUFNSqgImSXN1eHBvcnRhbC5Qcm90by5TZXJ2aWNlcy5SZWdpc3RyYXRpb27KAiZJc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXFJlZ2lzdHJhdGlvbuICMklzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcUmVnaXN0cmF0aW9uXEdQQk1ldGFkYXRh6gIpSXN1eHBvcnRhbDo6UHJvdG86OlNlcnZpY2VzOjpSZWdpc3RyYXRpb25iBnByb3RvMw", [file_isuxportal_resources_env_check]);

/**
 * Describes the message isuxportal.proto.services.registration.GetEnvCheckInformationResponse.
 * Use `create(GetEnvCheckInformationResponseSchema)` to create a new message.
 */
export const GetEnvCheckInformationResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_env_check, 0);

