// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/registration/env_check.proto (package isuxportal.proto.services.registration, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_env_check } from "../../resources/env_check_pb";

/**
 * Describes the file isuxportal/services/registration/env_check.proto.
 */
export const file_isuxportal_services_registration_env_check = /*@__PURE__*/
  fileDesc("CjBpc3V4cG9ydGFsL3NlcnZpY2VzL3JlZ2lzdHJhdGlvbi9lbnZfY2hlY2sucHJvdG8SJmlzdXhwb3J0YWwucHJvdG8uc2VydmljZXMucmVnaXN0cmF0aW9uIoMBCh5HZXRFbnZDaGVja0luZm9ybWF0aW9uUmVzcG9uc2USEAoIdGVtcGxhdGUYASABKAkSOgoGc3RhdHVzGAIgASgOMiouaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMuRW52Q2hlY2tTdGF0dXMSEwoLaW5zdGFuY2VfaXAYAyABKAlC1QIKKmNvbS5pc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLnJlZ2lzdHJhdGlvbkINRW52Q2hlY2tQcm90b1ABWlxnaXRodWIuY29tL2lzdWNvbi9pc3Vjb24xNC1wb3J0YWwvc3VwZXJ2aXNvci9kdW1teWJlbmNoL2dlbi9pc3V4cG9ydGFsL3NlcnZpY2VzL3JlZ2lzdHJhdGlvbqICBElQU1KqAiZJc3V4cG9ydGFsLlByb3RvLlNlcnZpY2VzLlJlZ2lzdHJhdGlvbsoCJklzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcUmVnaXN0cmF0aW9u4gIySXN1eHBvcnRhbFxQcm90b1xTZXJ2aWNlc1xSZWdpc3RyYXRpb25cR1BCTWV0YWRhdGHqAilJc3V4cG9ydGFsOjpQcm90bzo6U2VydmljZXM6OlJlZ2lzdHJhdGlvbmIGcHJvdG8z", [file_isuxportal_resources_env_check]);

/**
 * Describes the message isuxportal.proto.services.registration.GetEnvCheckInformationResponse.
 * Use `create(GetEnvCheckInformationResponseSchema)` to create a new message.
 */
export const GetEnvCheckInformationResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_env_check, 0);

