// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/registration/join.proto (package isuxportal.proto.services.registration, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/services/registration/join.proto.
 */
export const file_isuxportal_services_registration_join = /*@__PURE__*/
  fileDesc("Citpc3V4cG9ydGFsL3NlcnZpY2VzL3JlZ2lzdHJhdGlvbi9qb2luLnByb3RvEiZpc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLnJlZ2lzdHJhdGlvbiJaCg9Kb2luVGVhbVJlcXVlc3QSDwoHdGVhbV9pZBgBIAEoAxIUCgxpbnZpdGVfdG9rZW4YAiABKAkSDAoEbmFtZRgDIAEoCRISCgppc19zdHVkZW50GAQgASgIIhIKEEpvaW5UZWFtUmVzcG9uc2VCwAIKKmNvbS5pc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLnJlZ2lzdHJhdGlvbkIJSm9pblByb3RvUAFaS2dpdGh1Yi5jb20vaXN1Y29uL2lzdWNvbjE0LXBvcnRhbC9wcm90by5nby9pc3V4cG9ydGFsL3NlcnZpY2VzL3JlZ2lzdHJhdGlvbqICBElQU1KqAiZJc3V4cG9ydGFsLlByb3RvLlNlcnZpY2VzLlJlZ2lzdHJhdGlvbsoCJklzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcUmVnaXN0cmF0aW9u4gIySXN1eHBvcnRhbFxQcm90b1xTZXJ2aWNlc1xSZWdpc3RyYXRpb25cR1BCTWV0YWRhdGHqAilJc3V4cG9ydGFsOjpQcm90bzo6U2VydmljZXM6OlJlZ2lzdHJhdGlvbmIGcHJvdG8z");

/**
 * Describes the message isuxportal.proto.services.registration.JoinTeamRequest.
 * Use `create(JoinTeamRequestSchema)` to create a new message.
 */
export const JoinTeamRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_join, 0);

/**
 * Describes the message isuxportal.proto.services.registration.JoinTeamResponse.
 * Use `create(JoinTeamResponseSchema)` to create a new message.
 */
export const JoinTeamResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_join, 1);

