// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/registration/join.proto (package isuxportal.proto.services.registration, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/services/registration/join.proto.
 */
export const file_isuxportal_services_registration_join = /*@__PURE__*/
  fileDesc("Citpc3V4cG9ydGFsL3NlcnZpY2VzL3JlZ2lzdHJhdGlvbi9qb2luLnByb3RvEiZpc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLnJlZ2lzdHJhdGlvbiJwCg9Kb2luVGVhbVJlcXVlc3QSDwoHdGVhbV9pZBgBIAEoAxIUCgxpbnZpdGVfdG9rZW4YAiABKAkSDAoEbmFtZRgDIAEoCRISCgppc19zdHVkZW50GAQgASgIEhQKDGlzX2luX3BlcnNvbhgFIAEoCCISChBKb2luVGVhbVJlc3BvbnNlQsACCipjb20uaXN1eHBvcnRhbC5wcm90by5zZXJ2aWNlcy5yZWdpc3RyYXRpb25CCUpvaW5Qcm90b1ABWktnaXRodWIuY29tL2lzdWNvbi9pc3Vjb24xNC1wb3J0YWwvcHJvdG8uZ28vaXN1eHBvcnRhbC9zZXJ2aWNlcy9yZWdpc3RyYXRpb26iAgRJUFNSqgImSXN1eHBvcnRhbC5Qcm90by5TZXJ2aWNlcy5SZWdpc3RyYXRpb27KAiZJc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXFJlZ2lzdHJhdGlvbuICMklzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcUmVnaXN0cmF0aW9uXEdQQk1ldGFkYXRh6gIpSXN1eHBvcnRhbDo6UHJvdG86OlNlcnZpY2VzOjpSZWdpc3RyYXRpb25iBnByb3RvMw");

/**
 * Describes the message isuxportal.proto.services.registration.JoinTeamRequest.
 * Use `create(JoinTeamRequestSchema)` to create a new message.
 */
export const JoinTeamRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_join, 0);

/**
 * Describes the message isuxportal.proto.services.registration.JoinTeamResponse.
 * Use `create(JoinTeamResponseSchema)` to create a new message.
 */
export const JoinTeamResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_join, 1);

