// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/registration/session.proto (package isuxportal.proto.services.registration, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_team } from "../../resources/team_pb";
import { file_isuxportal_resources_coupon } from "../../resources/coupon_pb";
import { file_isuxportal_resources_env_check } from "../../resources/env_check_pb";

/**
 * Describes the file isuxportal/services/registration/session.proto.
 */
export const file_isuxportal_services_registration_session = /*@__PURE__*/
  fileDesc("Ci5pc3V4cG9ydGFsL3NlcnZpY2VzL3JlZ2lzdHJhdGlvbi9zZXNzaW9uLnByb3RvEiZpc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLnJlZ2lzdHJhdGlvbiJaChtHZXRSZWdpc3RyYXRpb25TZXNzaW9uUXVlcnkSDwoHdGVhbV9pZBgBIAEoAxIUCgxpbnZpdGVfdG9rZW4YAiABKAkSFAoMYnlwYXNzX3Rva2VuGBAgASgJIrcECh5HZXRSZWdpc3RyYXRpb25TZXNzaW9uUmVzcG9uc2USLgoEdGVhbRgBIAEoCzIgLmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzLlRlYW0SXQoGc3RhdHVzGAIgASgOMk0uaXN1eHBvcnRhbC5wcm90by5zZXJ2aWNlcy5yZWdpc3RyYXRpb24uR2V0UmVnaXN0cmF0aW9uU2Vzc2lvblJlc3BvbnNlLlN0YXR1cxIUCgxnaXRodWJfbG9naW4YAyABKAkSGQoRZ2l0aHViX2F2YXRhcl91cmwYBCABKAkSEwoLZGlzY29yZF90YWcYBSABKAkSGgoSZGlzY29yZF9hdmF0YXJfdXJsGAYgASgJEhkKEW1lbWJlcl9pbnZpdGVfdXJsGAcgASgJEhkKEWRpc2NvcmRfc2VydmVyX2lkGAggASgJEkQKEGVudl9jaGVja19zdGF0dXMYCSABKA4yKi5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcy5FbnZDaGVja1N0YXR1cxIyCgZjb3Vwb24YCiABKAsyIi5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcy5Db3Vwb24idAoGU3RhdHVzEgoKBkNMT1NFRBAAEhAKDE5PVF9KT0lOQUJMRRABEhEKDU5PVF9MT0dHRURfSU4QAhINCglDUkVBVEFCTEUQAxIMCghKT0lOQUJMRRAEEgoKBkpPSU5FRBAFEhAKDERJU1FVQUxJRklFRBAGIpEBChlVcGRhdGVSZWdpc3RyYXRpb25SZXF1ZXN0EhEKCXRlYW1fbmFtZRgBIAEoCRIMCgRuYW1lGAIgASgJEhUKDWVtYWlsX2FkZHJlc3MYAyABKAkSEgoKaXNfc3R1ZGVudBgEIAEoCBIUCgxpc19pbl9wZXJzb24YBSABKAgSEgoKYXZhdGFyX3VybBgGIAEoCSIcChpVcGRhdGVSZWdpc3RyYXRpb25SZXNwb25zZSIbChlEZWxldGVSZWdpc3RyYXRpb25SZXF1ZXN0IhwKGkRlbGV0ZVJlZ2lzdHJhdGlvblJlc3BvbnNlQsMCCipjb20uaXN1eHBvcnRhbC5wcm90by5zZXJ2aWNlcy5yZWdpc3RyYXRpb25CDFNlc3Npb25Qcm90b1ABWktnaXRodWIuY29tL2lzdWNvbi9pc3Vjb24xNC1wb3J0YWwvcHJvdG8uZ28vaXN1eHBvcnRhbC9zZXJ2aWNlcy9yZWdpc3RyYXRpb26iAgRJUFNSqgImSXN1eHBvcnRhbC5Qcm90by5TZXJ2aWNlcy5SZWdpc3RyYXRpb27KAiZJc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXFJlZ2lzdHJhdGlvbuICMklzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcUmVnaXN0cmF0aW9uXEdQQk1ldGFkYXRh6gIpSXN1eHBvcnRhbDo6UHJvdG86OlNlcnZpY2VzOjpSZWdpc3RyYXRpb25iBnByb3RvMw", [file_isuxportal_resources_team, file_isuxportal_resources_coupon, file_isuxportal_resources_env_check]);

/**
 * Describes the message isuxportal.proto.services.registration.GetRegistrationSessionQuery.
 * Use `create(GetRegistrationSessionQuerySchema)` to create a new message.
 */
export const GetRegistrationSessionQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_session, 0);

/**
 * Describes the message isuxportal.proto.services.registration.GetRegistrationSessionResponse.
 * Use `create(GetRegistrationSessionResponseSchema)` to create a new message.
 */
export const GetRegistrationSessionResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_session, 1);

/**
 * Describes the enum isuxportal.proto.services.registration.GetRegistrationSessionResponse.Status.
 */
export const GetRegistrationSessionResponse_StatusSchema = /*@__PURE__*/
  enumDesc(file_isuxportal_services_registration_session, 1, 0);

/**
 * @generated from enum isuxportal.proto.services.registration.GetRegistrationSessionResponse.Status
 */
export const GetRegistrationSessionResponse_Status = /*@__PURE__*/
  tsEnum(GetRegistrationSessionResponse_StatusSchema);

/**
 * Describes the message isuxportal.proto.services.registration.UpdateRegistrationRequest.
 * Use `create(UpdateRegistrationRequestSchema)` to create a new message.
 */
export const UpdateRegistrationRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_session, 2);

/**
 * Describes the message isuxportal.proto.services.registration.UpdateRegistrationResponse.
 * Use `create(UpdateRegistrationResponseSchema)` to create a new message.
 */
export const UpdateRegistrationResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_session, 3);

/**
 * Describes the message isuxportal.proto.services.registration.DeleteRegistrationRequest.
 * Use `create(DeleteRegistrationRequestSchema)` to create a new message.
 */
export const DeleteRegistrationRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_session, 4);

/**
 * Describes the message isuxportal.proto.services.registration.DeleteRegistrationResponse.
 * Use `create(DeleteRegistrationResponseSchema)` to create a new message.
 */
export const DeleteRegistrationResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_session, 5);

