// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/registration/session.proto (package isuxportal.proto.services.registration, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_team } from "../../resources/team_pb";
import { file_isuxportal_resources_coupon } from "../../resources/coupon_pb";

/**
 * Describes the file isuxportal/services/registration/session.proto.
 */
export const file_isuxportal_services_registration_session = /*@__PURE__*/
  fileDesc("Ci5pc3V4cG9ydGFsL3NlcnZpY2VzL3JlZ2lzdHJhdGlvbi9zZXNzaW9uLnByb3RvEiZpc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLnJlZ2lzdHJhdGlvbiJaChtHZXRSZWdpc3RyYXRpb25TZXNzaW9uUXVlcnkSDwoHdGVhbV9pZBgBIAEoAxIUCgxpbnZpdGVfdG9rZW4YAiABKAkSFAoMYnlwYXNzX3Rva2VuGBAgASgJIokECh5HZXRSZWdpc3RyYXRpb25TZXNzaW9uUmVzcG9uc2USLgoEdGVhbRgBIAEoCzIgLmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzLlRlYW0SXQoGc3RhdHVzGAIgASgOMk0uaXN1eHBvcnRhbC5wcm90by5zZXJ2aWNlcy5yZWdpc3RyYXRpb24uR2V0UmVnaXN0cmF0aW9uU2Vzc2lvblJlc3BvbnNlLlN0YXR1cxIUCgxnaXRodWJfbG9naW4YAyABKAkSGQoRZ2l0aHViX2F2YXRhcl91cmwYBCABKAkSEwoLZGlzY29yZF90YWcYBSABKAkSGgoSZGlzY29yZF9hdmF0YXJfdXJsGAYgASgJEhkKEW1lbWJlcl9pbnZpdGVfdXJsGAcgASgJEhkKEWRpc2NvcmRfc2VydmVyX2lkGAggASgJEhYKDmVudl9jaGVja19kb25lGAkgASgIEjIKBmNvdXBvbhgKIAEoCzIiLmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzLkNvdXBvbiJ0CgZTdGF0dXMSCgoGQ0xPU0VEEAASEAoMTk9UX0pPSU5BQkxFEAESEQoNTk9UX0xPR0dFRF9JThACEg0KCUNSRUFUQUJMRRADEgwKCEpPSU5BQkxFEAQSCgoGSk9JTkVEEAUSEAoMRElTUVVBTElGSUVEEAYiZwoZVXBkYXRlUmVnaXN0cmF0aW9uUmVxdWVzdBIRCgl0ZWFtX25hbWUYASABKAkSDAoEbmFtZRgCIAEoCRIVCg1lbWFpbF9hZGRyZXNzGAMgASgJEhIKCmlzX3N0dWRlbnQYBCABKAgiHAoaVXBkYXRlUmVnaXN0cmF0aW9uUmVzcG9uc2UiGwoZRGVsZXRlUmVnaXN0cmF0aW9uUmVxdWVzdCIcChpEZWxldGVSZWdpc3RyYXRpb25SZXNwb25zZULDAgoqY29tLmlzdXhwb3J0YWwucHJvdG8uc2VydmljZXMucmVnaXN0cmF0aW9uQgxTZXNzaW9uUHJvdG9QAVpLZ2l0aHViLmNvbS9pc3Vjb24vaXN1Y29uMTQtcG9ydGFsL3Byb3RvLmdvL2lzdXhwb3J0YWwvc2VydmljZXMvcmVnaXN0cmF0aW9uogIESVBTUqoCJklzdXhwb3J0YWwuUHJvdG8uU2VydmljZXMuUmVnaXN0cmF0aW9uygImSXN1eHBvcnRhbFxQcm90b1xTZXJ2aWNlc1xSZWdpc3RyYXRpb27iAjJJc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXFJlZ2lzdHJhdGlvblxHUEJNZXRhZGF0YeoCKUlzdXhwb3J0YWw6OlByb3RvOjpTZXJ2aWNlczo6UmVnaXN0cmF0aW9uYgZwcm90bzM", [file_isuxportal_resources_team, file_isuxportal_resources_coupon]);

/**
 * Describes the message isuxportal.proto.services.registration.GetRegistrationSessionQuery.
 * Use `create(GetRegistrationSessionQuerySchema)` to create a new message.
 */
export const GetRegistrationSessionQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_session, 0);

/**
 * Describes the message isuxportal.proto.services.registration.GetRegistrationSessionResponse.
 * Use `create(GetRegistrationSessionResponseSchema)` to create a new message.
 */
export const GetRegistrationSessionResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_session, 1);

/**
 * Describes the enum isuxportal.proto.services.registration.GetRegistrationSessionResponse.Status.
 */
export const GetRegistrationSessionResponse_StatusSchema = /*@__PURE__*/
  enumDesc(file_isuxportal_services_registration_session, 1, 0);

/**
 * @generated from enum isuxportal.proto.services.registration.GetRegistrationSessionResponse.Status
 */
export const GetRegistrationSessionResponse_Status = /*@__PURE__*/
  tsEnum(GetRegistrationSessionResponse_StatusSchema);

/**
 * Describes the message isuxportal.proto.services.registration.UpdateRegistrationRequest.
 * Use `create(UpdateRegistrationRequestSchema)` to create a new message.
 */
export const UpdateRegistrationRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_session, 2);

/**
 * Describes the message isuxportal.proto.services.registration.UpdateRegistrationResponse.
 * Use `create(UpdateRegistrationResponseSchema)` to create a new message.
 */
export const UpdateRegistrationResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_session, 3);

/**
 * Describes the message isuxportal.proto.services.registration.DeleteRegistrationRequest.
 * Use `create(DeleteRegistrationRequestSchema)` to create a new message.
 */
export const DeleteRegistrationRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_session, 4);

/**
 * Describes the message isuxportal.proto.services.registration.DeleteRegistrationResponse.
 * Use `create(DeleteRegistrationResponseSchema)` to create a new message.
 */
export const DeleteRegistrationResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_registration_session, 5);

