// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/registration/session.proto (package isuxportal.proto.services.registration, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Team } from "../../resources/team_pb";
import type { EnvCheckStatus } from "../../resources/env_check_pb";
import type { Coupon } from "../../resources/coupon_pb";

/**
 * Describes the file isuxportal/services/registration/session.proto.
 */
export declare const file_isuxportal_services_registration_session: GenFile;

/**
 * query parameter
 *
 * @generated from message isuxportal.proto.services.registration.GetRegistrationSessionQuery
 */
export declare type GetRegistrationSessionQuery = Message<"isuxportal.proto.services.registration.GetRegistrationSessionQuery"> & {
  /**
   * @generated from field: int64 team_id = 1;
   */
  teamId: bigint;

  /**
   * @generated from field: string invite_token = 2;
   */
  inviteToken: string;

  /**
   * @generated from field: string bypass_token = 16;
   */
  bypassToken: string;
};

/**
 * Describes the message isuxportal.proto.services.registration.GetRegistrationSessionQuery.
 * Use `create(GetRegistrationSessionQuerySchema)` to create a new message.
 */
export declare const GetRegistrationSessionQuerySchema: GenMessage<GetRegistrationSessionQuery>;

/**
 * @generated from message isuxportal.proto.services.registration.GetRegistrationSessionResponse
 */
export declare type GetRegistrationSessionResponse = Message<"isuxportal.proto.services.registration.GetRegistrationSessionResponse"> & {
  /**
   * @generated from field: isuxportal.proto.resources.Team team = 1;
   */
  team?: Team;

  /**
   * @generated from field: isuxportal.proto.services.registration.GetRegistrationSessionResponse.Status status = 2;
   */
  status: GetRegistrationSessionResponse_Status;

  /**
   * @generated from field: string github_login = 3;
   */
  githubLogin: string;

  /**
   * @generated from field: string github_avatar_url = 4;
   */
  githubAvatarUrl: string;

  /**
   * @generated from field: string discord_tag = 5;
   */
  discordTag: string;

  /**
   * @generated from field: string discord_avatar_url = 6;
   */
  discordAvatarUrl: string;

  /**
   * @generated from field: string member_invite_url = 7;
   */
  memberInviteUrl: string;

  /**
   * @generated from field: string discord_server_id = 8;
   */
  discordServerId: string;

  /**
   * @generated from field: isuxportal.proto.resources.EnvCheckStatus env_check_status = 9;
   */
  envCheckStatus: EnvCheckStatus;

  /**
   * @generated from field: isuxportal.proto.resources.Coupon coupon = 10;
   */
  coupon?: Coupon;
};

/**
 * Describes the message isuxportal.proto.services.registration.GetRegistrationSessionResponse.
 * Use `create(GetRegistrationSessionResponseSchema)` to create a new message.
 */
export declare const GetRegistrationSessionResponseSchema: GenMessage<GetRegistrationSessionResponse>;

/**
 * @generated from enum isuxportal.proto.services.registration.GetRegistrationSessionResponse.Status
 */
export enum GetRegistrationSessionResponse_Status {
  /**
   * @generated from enum value: CLOSED = 0;
   */
  CLOSED = 0,

  /**
   * @generated from enum value: NOT_JOINABLE = 1;
   */
  NOT_JOINABLE = 1,

  /**
   * @generated from enum value: NOT_LOGGED_IN = 2;
   */
  NOT_LOGGED_IN = 2,

  /**
   * @generated from enum value: CREATABLE = 3;
   */
  CREATABLE = 3,

  /**
   * @generated from enum value: JOINABLE = 4;
   */
  JOINABLE = 4,

  /**
   * @generated from enum value: JOINED = 5;
   */
  JOINED = 5,

  /**
   * @generated from enum value: DISQUALIFIED = 6;
   */
  DISQUALIFIED = 6,
}

/**
 * Describes the enum isuxportal.proto.services.registration.GetRegistrationSessionResponse.Status.
 */
export declare const GetRegistrationSessionResponse_StatusSchema: GenEnum<GetRegistrationSessionResponse_Status>;

/**
 * @generated from message isuxportal.proto.services.registration.UpdateRegistrationRequest
 */
export declare type UpdateRegistrationRequest = Message<"isuxportal.proto.services.registration.UpdateRegistrationRequest"> & {
  /**
   * @generated from field: string team_name = 1;
   */
  teamName: string;

  /**
   * contestant name
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string email_address = 3;
   */
  emailAddress: string;

  /**
   * @generated from field: bool is_student = 4;
   */
  isStudent: boolean;

  /**
   * @generated from field: bool is_in_person = 5;
   */
  isInPerson: boolean;

  /**
   * @generated from field: string avatar_url = 6;
   */
  avatarUrl: string;
};

/**
 * Describes the message isuxportal.proto.services.registration.UpdateRegistrationRequest.
 * Use `create(UpdateRegistrationRequestSchema)` to create a new message.
 */
export declare const UpdateRegistrationRequestSchema: GenMessage<UpdateRegistrationRequest>;

/**
 * @generated from message isuxportal.proto.services.registration.UpdateRegistrationResponse
 */
export declare type UpdateRegistrationResponse = Message<"isuxportal.proto.services.registration.UpdateRegistrationResponse"> & {
};

/**
 * Describes the message isuxportal.proto.services.registration.UpdateRegistrationResponse.
 * Use `create(UpdateRegistrationResponseSchema)` to create a new message.
 */
export declare const UpdateRegistrationResponseSchema: GenMessage<UpdateRegistrationResponse>;

/**
 * @generated from message isuxportal.proto.services.registration.DeleteRegistrationRequest
 */
export declare type DeleteRegistrationRequest = Message<"isuxportal.proto.services.registration.DeleteRegistrationRequest"> & {
};

/**
 * Describes the message isuxportal.proto.services.registration.DeleteRegistrationRequest.
 * Use `create(DeleteRegistrationRequestSchema)` to create a new message.
 */
export declare const DeleteRegistrationRequestSchema: GenMessage<DeleteRegistrationRequest>;

/**
 * @generated from message isuxportal.proto.services.registration.DeleteRegistrationResponse
 */
export declare type DeleteRegistrationResponse = Message<"isuxportal.proto.services.registration.DeleteRegistrationResponse"> & {
};

/**
 * Describes the message isuxportal.proto.services.registration.DeleteRegistrationResponse.
 * Use `create(DeleteRegistrationResponseSchema)` to create a new message.
 */
export declare const DeleteRegistrationResponseSchema: GenMessage<DeleteRegistrationResponse>;

