# https://docs.newrelic.com/docs/agents/ruby-agent/installation-configuration/ruby-agent-configuration
# license_key: ENV['NEW_RELIC_LICENSE_KEY']

common: &default_settings
  app_name: <%= 'ISUCON14 Portal(' + (ENV['MONITOR_ENV'] || development) + ')' %>
  log_level: info
  browser_monitoring:
    auto_instrument: false

development:
  <<: *default_settings
  agent_enabled: true

test:
  <<: *default_settings
  agent_enabled: false
  monitor_mode: false

production:
  <<: *default_settings
  agent_enabled: true
