// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/audience/dashboard.proto (package isuxportal.proto.services.audience, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_leaderboard } from "../../resources/leaderboard_pb";

/**
 * Describes the file isuxportal/services/audience/dashboard.proto.
 */
export const file_isuxportal_services_audience_dashboard = /*@__PURE__*/
  fileDesc("Cixpc3V4cG9ydGFsL3NlcnZpY2VzL2F1ZGllbmNlL2Rhc2hib2FyZC5wcm90bxIiaXN1eHBvcnRhbC5wcm90by5zZXJ2aWNlcy5hdWRpZW5jZSIQCg5EYXNoYm9hcmRRdWVyeSJRChFEYXNoYm9hcmRSZXNwb25zZRI8CgtsZWFkZXJib2FyZBgBIAEoCzInLmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzLkxlYWRlcmJvYXJkIhQKElNvbG9EYXNoYm9hcmRRdWVyeSJeChVTb2xvRGFzaGJvYXJkUmVzcG9uc2USRQoQbGVhZGVyYm9hcmRfaXRlbRgBIAEoCzIrLmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzLkxlYWRlcmJvYXJkSXRlbUK+AgomY29tLmlzdXhwb3J0YWwucHJvdG8uc2VydmljZXMuYXVkaWVuY2VCDkRhc2hib2FyZFByb3RvUAFaWGdpdGh1Yi5jb20vaXN1Y29uL2lzdWNvbjE0LXBvcnRhbC9zdXBlcnZpc29yL2R1bW15YmVuY2gvZ2VuL2lzdXhwb3J0YWwvc2VydmljZXMvYXVkaWVuY2WiAgRJUFNBqgIiSXN1eHBvcnRhbC5Qcm90by5TZXJ2aWNlcy5BdWRpZW5jZcoCIklzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcQXVkaWVuY2XiAi5Jc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXEF1ZGllbmNlXEdQQk1ldGFkYXRh6gIlSXN1eHBvcnRhbDo6UHJvdG86OlNlcnZpY2VzOjpBdWRpZW5jZWIGcHJvdG8z", [file_isuxportal_resources_leaderboard]);

/**
 * Describes the message isuxportal.proto.services.audience.DashboardQuery.
 * Use `create(DashboardQuerySchema)` to create a new message.
 */
export const DashboardQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_audience_dashboard, 0);

/**
 * Describes the message isuxportal.proto.services.audience.DashboardResponse.
 * Use `create(DashboardResponseSchema)` to create a new message.
 */
export const DashboardResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_audience_dashboard, 1);

/**
 * Describes the message isuxportal.proto.services.audience.SoloDashboardQuery.
 * Use `create(SoloDashboardQuerySchema)` to create a new message.
 */
export const SoloDashboardQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_audience_dashboard, 2);

/**
 * Describes the message isuxportal.proto.services.audience.SoloDashboardResponse.
 * Use `create(SoloDashboardResponseSchema)` to create a new message.
 */
export const SoloDashboardResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_audience_dashboard, 3);

