// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/audience/team_list.proto (package isuxportal.proto.services.audience, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/services/audience/team_list.proto.
 */
export const file_isuxportal_services_audience_team_list = /*@__PURE__*/
  fileDesc("Cixpc3V4cG9ydGFsL3NlcnZpY2VzL2F1ZGllbmNlL3RlYW1fbGlzdC5wcm90bxIiaXN1eHBvcnRhbC5wcm90by5zZXJ2aWNlcy5hdWRpZW5jZSISChBMaXN0VGVhbXNSZXF1ZXN0ItwBChFMaXN0VGVhbXNSZXNwb25zZRJRCgV0ZWFtcxgBIAMoCzJCLmlzdXhwb3J0YWwucHJvdG8uc2VydmljZXMuYXVkaWVuY2UuTGlzdFRlYW1zUmVzcG9uc2UuVGVhbUxpc3RJdGVtGnQKDFRlYW1MaXN0SXRlbRIPCgd0ZWFtX2lkGAEgASgDEgwKBG5hbWUYAiABKAkSFAoMbWVtYmVyX25hbWVzGAMgAygJEhsKE2ZpbmFsX3BhcnRpY2lwYXRpb24YBCABKAgSEgoKaXNfc3R1ZGVudBgFIAEoCEK9AgomY29tLmlzdXhwb3J0YWwucHJvdG8uc2VydmljZXMuYXVkaWVuY2VCDVRlYW1MaXN0UHJvdG9QAVpYZ2l0aHViLmNvbS9pc3Vjb24vaXN1Y29uMTQtcG9ydGFsL3N1cGVydmlzb3IvZHVtbXliZW5jaC9nZW4vaXN1eHBvcnRhbC9zZXJ2aWNlcy9hdWRpZW5jZaICBElQU0GqAiJJc3V4cG9ydGFsLlByb3RvLlNlcnZpY2VzLkF1ZGllbmNlygIiSXN1eHBvcnRhbFxQcm90b1xTZXJ2aWNlc1xBdWRpZW5jZeICLklzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcQXVkaWVuY2VcR1BCTWV0YWRhdGHqAiVJc3V4cG9ydGFsOjpQcm90bzo6U2VydmljZXM6OkF1ZGllbmNlYgZwcm90bzM");

/**
 * Describes the message isuxportal.proto.services.audience.ListTeamsRequest.
 * Use `create(ListTeamsRequestSchema)` to create a new message.
 */
export const ListTeamsRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_audience_team_list, 0);

/**
 * Describes the message isuxportal.proto.services.audience.ListTeamsResponse.
 * Use `create(ListTeamsResponseSchema)` to create a new message.
 */
export const ListTeamsResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_audience_team_list, 1);

/**
 * Describes the message isuxportal.proto.services.audience.ListTeamsResponse.TeamListItem.
 * Use `create(ListTeamsResponse_TeamListItemSchema)` to create a new message.
 */
export const ListTeamsResponse_TeamListItemSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_audience_team_list, 1, 0);

