// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/error.proto (package isuxportal.proto, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/error.proto.
 */
export const file_isuxportal_error = /*@__PURE__*/
  fileDesc("ChZpc3V4cG9ydGFsL2Vycm9yLnByb3RvEhBpc3V4cG9ydGFsLnByb3RvIvABCgVFcnJvchIMCgRjb2RlGAEgASgFEgwKBG5hbWUYAiABKAkSFQoNaHVtYW5fbWVzc2FnZRgDIAEoCRIaChJodW1hbl9kZXNjcmlwdGlvbnMYBCADKAkSNQoKZGVidWdfaW5mbxgQIAEoCzIhLmlzdXhwb3J0YWwucHJvdG8uRXJyb3IuRGVidWdJbmZvGmEKCURlYnVnSW5mbxIRCglleGNlcHRpb24YASABKAkSDQoFdHJhY2UYAiADKAkSGQoRYXBwbGljYXRpb25fdHJhY2UYAyADKAkSFwoPZnJhbWV3b3JrX3RyYWNlGAQgAygJQroBChRjb20uaXN1eHBvcnRhbC5wcm90b0IKRXJyb3JQcm90b1ABWjVnaXRodWIuY29tL2lzdWNvbi9pc3Vjb24xNC1wb3J0YWwvcHJvdG8uZ28vaXN1eHBvcnRhbKICA0lQWKoCEElzdXhwb3J0YWwuUHJvdG/KAhBJc3V4cG9ydGFsXFByb3Rv4gIcSXN1eHBvcnRhbFxQcm90b1xHUEJNZXRhZGF0YeoCEUlzdXhwb3J0YWw6OlByb3RvYgZwcm90bzM");

/**
 * Describes the message isuxportal.proto.Error.
 * Use `create(ErrorSchema)` to create a new message.
 */
export const ErrorSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_error, 0);

/**
 * Describes the message isuxportal.proto.Error.DebugInfo.
 * Use `create(Error_DebugInfoSchema)` to create a new message.
 */
export const Error_DebugInfoSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_error, 0, 0);

