// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/misc/bypass_token.proto (package isuxportal.proto.misc, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file isuxportal/misc/bypass_token.proto.
 */
export declare const file_isuxportal_misc_bypass_token: GenFile;

/**
 * @generated from message isuxportal.proto.misc.BypassTokenPayload
 */
export declare type BypassTokenPayload = Message<"isuxportal.proto.misc.BypassTokenPayload"> & {
  /**
   * @generated from field: string filler = 1;
   */
  filler: string;

  /**
   * @generated from field: int64 expiry = 2;
   */
  expiry: bigint;

  /**
   * @generated from field: repeated isuxportal.proto.misc.BypassTokenPayload.Usage usages = 3;
   */
  usages: BypassTokenPayload_Usage[];
};

/**
 * Describes the message isuxportal.proto.misc.BypassTokenPayload.
 * Use `create(BypassTokenPayloadSchema)` to create a new message.
 */
export declare const BypassTokenPayloadSchema: GenMessage<BypassTokenPayload>;

/**
 * @generated from enum isuxportal.proto.misc.BypassTokenPayload.Usage
 */
export enum BypassTokenPayload_Usage {
  /**
   * @generated from enum value: CREATE_TEAM = 0;
   */
  CREATE_TEAM = 0,

  /**
   * @generated from enum value: JOIN_TEAM = 1;
   */
  JOIN_TEAM = 1,

  /**
   * @generated from enum value: HIDDEN_TEAM = 2;
   */
  HIDDEN_TEAM = 2,

  /**
   * @generated from enum value: LEAVE_TEAM = 3;
   */
  LEAVE_TEAM = 3,
}

/**
 * Describes the enum isuxportal.proto.misc.BypassTokenPayload.Usage.
 */
export declare const BypassTokenPayload_UsageSchema: GenEnum<BypassTokenPayload_Usage>;

