// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/misc/bypass_token.proto (package isuxportal.proto.misc, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/misc/bypass_token.proto.
 */
export const file_isuxportal_misc_bypass_token = /*@__PURE__*/
  fileDesc("CiJpc3V4cG9ydGFsL21pc2MvYnlwYXNzX3Rva2VuLnByb3RvEhVpc3V4cG9ydGFsLnByb3RvLm1pc2MivwEKEkJ5cGFzc1Rva2VuUGF5bG9hZBIOCgZmaWxsZXIYASABKAkSDgoGZXhwaXJ5GAIgASgDEj8KBnVzYWdlcxgDIAMoDjIvLmlzdXhwb3J0YWwucHJvdG8ubWlzYy5CeXBhc3NUb2tlblBheWxvYWQuVXNhZ2UiSAoFVXNhZ2USDwoLQ1JFQVRFX1RFQU0QABINCglKT0lOX1RFQU0QARIPCgtISURERU5fVEVBTRACEg4KCkxFQVZFX1RFQU0QA0LwAQoZY29tLmlzdXhwb3J0YWwucHJvdG8ubWlzY0IQQnlwYXNzVG9rZW5Qcm90b1ABWktnaXRodWIuY29tL2lzdWNvbi9pc3Vjb24xNC1wb3J0YWwvc3VwZXJ2aXNvci9kdW1teWJlbmNoL2dlbi9pc3V4cG9ydGFsL21pc2OiAgNJUE2qAhVJc3V4cG9ydGFsLlByb3RvLk1pc2PKAhVJc3V4cG9ydGFsXFByb3RvXE1pc2PiAiFJc3V4cG9ydGFsXFByb3RvXE1pc2NcR1BCTWV0YWRhdGHqAhdJc3V4cG9ydGFsOjpQcm90bzo6TWlzY2IGcHJvdG8z");

/**
 * Describes the message isuxportal.proto.misc.BypassTokenPayload.
 * Use `create(BypassTokenPayloadSchema)` to create a new message.
 */
export const BypassTokenPayloadSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_misc_bypass_token, 0);

/**
 * Describes the enum isuxportal.proto.misc.BypassTokenPayload.Usage.
 */
export const BypassTokenPayload_UsageSchema = /*@__PURE__*/
  enumDesc(file_isuxportal_misc_bypass_token, 0, 0);

/**
 * @generated from enum isuxportal.proto.misc.BypassTokenPayload.Usage
 */
export const BypassTokenPayload_Usage = /*@__PURE__*/
  tsEnum(BypassTokenPayload_UsageSchema);

