// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/misc/leaderboard_etag.proto (package isuxportal.proto.misc, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file isuxportal/misc/leaderboard_etag.proto.
 */
export const file_isuxportal_misc_leaderboard_etag = /*@__PURE__*/
  fileDesc("CiZpc3V4cG9ydGFsL21pc2MvbGVhZGVyYm9hcmRfZXRhZy5wcm90bxIVaXN1eHBvcnRhbC5wcm90by5taXNjIrYCCg9MZWFkZXJib2FyZEV0YWcSDQoFYWRtaW4YASABKAgSDwoHdGVhbV9pZBgCIAEoAxISCgp0ZWFtX2NvdW50GAMgASgDEjUKEXRlYW1fbGFzdF91cGRhdGVkGAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIYChBsYXRlc3RfcmVzdWx0X2lkGAUgASgDEhoKEmxhdGVzdF9wcm9ncmVzc19pZBgGIAEoAxIUCgxoYXNfcHJvZ3Jlc3MYByABKAgSNAoQbGF0ZXN0X3Jlc3VsdF9hdBgIIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASNgoSbGF0ZXN0X3Byb2dyZXNzX2F0GAkgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEL0AQoZY29tLmlzdXhwb3J0YWwucHJvdG8ubWlzY0IUTGVhZGVyYm9hcmRFdGFnUHJvdG9QAVpLZ2l0aHViLmNvbS9pc3Vjb24vaXN1Y29uMTQtcG9ydGFsL3N1cGVydmlzb3IvZHVtbXliZW5jaC9nZW4vaXN1eHBvcnRhbC9taXNjogIDSVBNqgIVSXN1eHBvcnRhbC5Qcm90by5NaXNjygIVSXN1eHBvcnRhbFxQcm90b1xNaXNj4gIhSXN1eHBvcnRhbFxQcm90b1xNaXNjXEdQQk1ldGFkYXRh6gIXSXN1eHBvcnRhbDo6UHJvdG86Ok1pc2NiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * Describes the message isuxportal.proto.misc.LeaderboardEtag.
 * Use `create(LeaderboardEtagSchema)` to create a new message.
 */
export const LeaderboardEtagSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_misc_leaderboard_etag, 0);

