// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/misc/leaderboard_etag.proto (package isuxportal.proto.misc, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file isuxportal/misc/leaderboard_etag.proto.
 */
export declare const file_isuxportal_misc_leaderboard_etag: GenFile;

/**
 * @generated from message isuxportal.proto.misc.LeaderboardEtag
 */
export declare type LeaderboardEtag = Message<"isuxportal.proto.misc.LeaderboardEtag"> & {
  /**
   * @generated from field: bool admin = 1;
   */
  admin: boolean;

  /**
   * @generated from field: int64 team_id = 2;
   */
  teamId: bigint;

  /**
   * @generated from field: int64 team_count = 3;
   */
  teamCount: bigint;

  /**
   * @generated from field: google.protobuf.Timestamp team_last_updated = 4;
   */
  teamLastUpdated?: Timestamp;

  /**
   * @generated from field: int64 latest_result_id = 5;
   */
  latestResultId: bigint;

  /**
   * @generated from field: int64 latest_progress_id = 6;
   */
  latestProgressId: bigint;

  /**
   * @generated from field: bool has_progress = 7;
   */
  hasProgress: boolean;

  /**
   * @generated from field: google.protobuf.Timestamp latest_result_at = 8;
   */
  latestResultAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp latest_progress_at = 9;
   */
  latestProgressAt?: Timestamp;
};

/**
 * Describes the message isuxportal.proto.misc.LeaderboardEtag.
 * Use `create(LeaderboardEtagSchema)` to create a new message.
 */
export declare const LeaderboardEtagSchema: GenMessage<LeaderboardEtag>;

