// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/misc/bot/support.proto (package isuxportal.proto.misc.bot, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/misc/bot/support.proto.
 */
export const file_isuxportal_misc_bot_support = /*@__PURE__*/
  fileDesc("CiFpc3V4cG9ydGFsL21pc2MvYm90L3N1cHBvcnQucHJvdG8SGWlzdXhwb3J0YWwucHJvdG8ubWlzYy5ib3QioAEKD1N1cHBvcnRDb21tSW5mbxI/CgV1c2FnZRgCIAEoCzIwLmlzdXhwb3J0YWwucHJvdG8ubWlzYy5ib3QuU3VwcG9ydENvbW1JbmZvLlVzYWdlGkwKBVVzYWdlEhgKEG1lc3NhZ2VfaWRfc2luY2UYASABKAQSDwoHdGVhbV9pZBgCIAEoAxIYChBjbGFyaWZpY2F0aW9uX2lkGAMgASgDQoYCCh1jb20uaXN1eHBvcnRhbC5wcm90by5taXNjLmJvdEIMU3VwcG9ydFByb3RvUAFaT2dpdGh1Yi5jb20vaXN1Y29uL2lzdWNvbjE0LXBvcnRhbC9zdXBlcnZpc29yL2R1bW15YmVuY2gvZ2VuL2lzdXhwb3J0YWwvbWlzYy9ib3SiAgRJUE1CqgIZSXN1eHBvcnRhbC5Qcm90by5NaXNjLkJvdMoCGUlzdXhwb3J0YWxcUHJvdG9cTWlzY1xCb3TiAiVJc3V4cG9ydGFsXFByb3RvXE1pc2NcQm90XEdQQk1ldGFkYXRh6gIcSXN1eHBvcnRhbDo6UHJvdG86Ok1pc2M6OkJvdGIGcHJvdG8z");

/**
 * Describes the message isuxportal.proto.misc.bot.SupportCommInfo.
 * Use `create(SupportCommInfoSchema)` to create a new message.
 */
export const SupportCommInfoSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_misc_bot_support, 0);

/**
 * Describes the message isuxportal.proto.misc.bot.SupportCommInfo.Usage.
 * Use `create(SupportCommInfo_UsageSchema)` to create a new message.
 */
export const SupportCommInfo_UsageSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_misc_bot_support, 0, 0);

