// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/misc/bot/support.proto (package isuxportal.proto.misc.bot, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file isuxportal/misc/bot/support.proto.
 */
export declare const file_isuxportal_misc_bot_support: GenFile;

/**
 * @generated from message isuxportal.proto.misc.bot.SupportCommInfo
 */
export declare type SupportCommInfo = Message<"isuxportal.proto.misc.bot.SupportCommInfo"> & {
  /**
   * @generated from field: isuxportal.proto.misc.bot.SupportCommInfo.Usage usage = 2;
   */
  usage?: SupportCommInfo_Usage;
};

/**
 * Describes the message isuxportal.proto.misc.bot.SupportCommInfo.
 * Use `create(SupportCommInfoSchema)` to create a new message.
 */
export declare const SupportCommInfoSchema: GenMessage<SupportCommInfo>;

/**
 * @generated from message isuxportal.proto.misc.bot.SupportCommInfo.Usage
 */
export declare type SupportCommInfo_Usage = Message<"isuxportal.proto.misc.bot.SupportCommInfo.Usage"> & {
  /**
   * @generated from field: uint64 message_id_since = 1;
   */
  messageIdSince: bigint;

  /**
   * @generated from field: int64 team_id = 2;
   */
  teamId: bigint;

  /**
   * @generated from field: int64 clarification_id = 3;
   */
  clarificationId: bigint;
};

/**
 * Describes the message isuxportal.proto.misc.bot.SupportCommInfo.Usage.
 * Use `create(SupportCommInfo_UsageSchema)` to create a new message.
 */
export declare const SupportCommInfo_UsageSchema: GenMessage<SupportCommInfo_Usage>;

