required_version: ">= 1.7.10, < 2.0.0"
region: ap-northeast-1
cluster: "{{ must_env `ENV` }}-portal"
service: app
service_definition: servicedef/app.jsonnet
task_definition: taskdef/app.jsonnet
timeout: 10m0s
plugins:
  - name: tfstate
    config:
      url: "s3://tfstate-{{ must_env `ENV` }}-portal-isucon14/terraform.tfstate"
filter_command: peco
