FROM public.ecr.aws/docker/library/rust:bookworm AS builder

RUN apt-get -y update && apt-get -y install cmake
RUN mkdir /tmp/isucon14-portal
COPY . /tmp/isucon14-portal/supervisor
WORKDIR /tmp/isucon14-portal/supervisor
RUN cargo build --release --bin isuxportal-supervisor
RUN install target/release/isuxportal-supervisor /usr/local/bin/isuxportal-supervisor

FROM public.ecr.aws/docker/library/golang:bookworm AS benchmarker

COPY . /tmp/isucon14-portal/benchmarker
WORKDIR /tmp/isucon14-portal/benchmarker/dummybench
RUN go build -o /usr/local/bin/dummybench /tmp/isucon14-portal/benchmarker/dummybench

FROM public.ecr.aws/docker/library/debian:bookworm-slim

RUN apt-get update
RUN apt install -y ca-certificates openssl curl
RUN bash -c "curl -sSfL https://raw.githubusercontent.com/aquaproj/aqua-installer/v3.1.0/aqua-installer | bash"
ENV PATH=/root/.local/share/aquaproj-aqua/bin:$PATH
ENV AQUA_GLOBAL_CONFIG=/etc/aqua/aqua.yaml
COPY aqua.yaml /etc/aqua/
RUN aqua i -a
COPY --from=builder /usr/local/bin/isuxportal-supervisor /usr/local/bin/isuxportal-supervisor
COPY --from=benchmarker /usr/local/bin/dummybench /usr/local/bin/dummybench
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["/usr/local/bin/isuxportal-supervisor", "/usr/local/bin/dummybench"]
