// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/contestant/clarifications.proto (package isuxportal.proto.services.contestant, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Clarification } from "../../resources/clarification_pb";

/**
 * Describes the file isuxportal/services/contestant/clarifications.proto.
 */
export declare const file_isuxportal_services_contestant_clarifications: GenFile;

/**
 * @generated from message isuxportal.proto.services.contestant.ListClarificationsQuery
 */
export declare type ListClarificationsQuery = Message<"isuxportal.proto.services.contestant.ListClarificationsQuery"> & {
};

/**
 * Describes the message isuxportal.proto.services.contestant.ListClarificationsQuery.
 * Use `create(ListClarificationsQuerySchema)` to create a new message.
 */
export declare const ListClarificationsQuerySchema: GenMessage<ListClarificationsQuery>;

/**
 * @generated from message isuxportal.proto.services.contestant.ListClarificationsResponse
 */
export declare type ListClarificationsResponse = Message<"isuxportal.proto.services.contestant.ListClarificationsResponse"> & {
  /**
   * @generated from field: repeated isuxportal.proto.resources.Clarification clarifications = 1;
   */
  clarifications: Clarification[];
};

/**
 * Describes the message isuxportal.proto.services.contestant.ListClarificationsResponse.
 * Use `create(ListClarificationsResponseSchema)` to create a new message.
 */
export declare const ListClarificationsResponseSchema: GenMessage<ListClarificationsResponse>;

/**
 * @generated from message isuxportal.proto.services.contestant.RequestClarificationRequest
 */
export declare type RequestClarificationRequest = Message<"isuxportal.proto.services.contestant.RequestClarificationRequest"> & {
  /**
   * @generated from field: string question = 1;
   */
  question: string;
};

/**
 * Describes the message isuxportal.proto.services.contestant.RequestClarificationRequest.
 * Use `create(RequestClarificationRequestSchema)` to create a new message.
 */
export declare const RequestClarificationRequestSchema: GenMessage<RequestClarificationRequest>;

/**
 * @generated from message isuxportal.proto.services.contestant.RequestClarificationResponse
 */
export declare type RequestClarificationResponse = Message<"isuxportal.proto.services.contestant.RequestClarificationResponse"> & {
  /**
   * @generated from field: isuxportal.proto.resources.Clarification clarification = 1;
   */
  clarification?: Clarification;
};

/**
 * Describes the message isuxportal.proto.services.contestant.RequestClarificationResponse.
 * Use `create(RequestClarificationResponseSchema)` to create a new message.
 */
export declare const RequestClarificationResponseSchema: GenMessage<RequestClarificationResponse>;

