// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/contestant/clarifications.proto (package isuxportal.proto.services.contestant, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_clarification } from "../../resources/clarification_pb";

/**
 * Describes the file isuxportal/services/contestant/clarifications.proto.
 */
export const file_isuxportal_services_contestant_clarifications = /*@__PURE__*/
  fileDesc("CjNpc3V4cG9ydGFsL3NlcnZpY2VzL2NvbnRlc3RhbnQvY2xhcmlmaWNhdGlvbnMucHJvdG8SJGlzdXhwb3J0YWwucHJvdG8uc2VydmljZXMuY29udGVzdGFudCIZChdMaXN0Q2xhcmlmaWNhdGlvbnNRdWVyeSJfChpMaXN0Q2xhcmlmaWNhdGlvbnNSZXNwb25zZRJBCg5jbGFyaWZpY2F0aW9ucxgBIAMoCzIpLmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzLkNsYXJpZmljYXRpb24iLwobUmVxdWVzdENsYXJpZmljYXRpb25SZXF1ZXN0EhAKCHF1ZXN0aW9uGAEgASgJImAKHFJlcXVlc3RDbGFyaWZpY2F0aW9uUmVzcG9uc2USQAoNY2xhcmlmaWNhdGlvbhgBIAEoCzIpLmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzLkNsYXJpZmljYXRpb25CvgIKKGNvbS5pc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLmNvbnRlc3RhbnRCE0NsYXJpZmljYXRpb25zUHJvdG9QAVpJZ2l0aHViLmNvbS9pc3Vjb24vaXN1Y29uMTQtcG9ydGFsL3Byb3RvLmdvL2lzdXhwb3J0YWwvc2VydmljZXMvY29udGVzdGFudKICBElQU0OqAiRJc3V4cG9ydGFsLlByb3RvLlNlcnZpY2VzLkNvbnRlc3RhbnTKAiRJc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXENvbnRlc3RhbnTiAjBJc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXENvbnRlc3RhbnRcR1BCTWV0YWRhdGHqAidJc3V4cG9ydGFsOjpQcm90bzo6U2VydmljZXM6OkNvbnRlc3RhbnRiBnByb3RvMw", [file_isuxportal_resources_clarification]);

/**
 * Describes the message isuxportal.proto.services.contestant.ListClarificationsQuery.
 * Use `create(ListClarificationsQuerySchema)` to create a new message.
 */
export const ListClarificationsQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_contestant_clarifications, 0);

/**
 * Describes the message isuxportal.proto.services.contestant.ListClarificationsResponse.
 * Use `create(ListClarificationsResponseSchema)` to create a new message.
 */
export const ListClarificationsResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_contestant_clarifications, 1);

/**
 * Describes the message isuxportal.proto.services.contestant.RequestClarificationRequest.
 * Use `create(RequestClarificationRequestSchema)` to create a new message.
 */
export const RequestClarificationRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_contestant_clarifications, 2);

/**
 * Describes the message isuxportal.proto.services.contestant.RequestClarificationResponse.
 * Use `create(RequestClarificationResponseSchema)` to create a new message.
 */
export const RequestClarificationResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_contestant_clarifications, 3);

