// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/contestant/cloud_formation.proto (package isuxportal.proto.services.contestant, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/services/contestant/cloud_formation.proto.
 */
export const file_isuxportal_services_contestant_cloud_formation = /*@__PURE__*/
  fileDesc("CjRpc3V4cG9ydGFsL3NlcnZpY2VzL2NvbnRlc3RhbnQvY2xvdWRfZm9ybWF0aW9uLnByb3RvEiRpc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLmNvbnRlc3RhbnQiGAoWR2V0Q2xvdWRGb3JtYXRpb25RdWVyeSItChlHZXRDbG91ZEZvcm1hdGlvblJlc3BvbnNlEhAKCHRlbXBsYXRlGAEgASgJQr4CCihjb20uaXN1eHBvcnRhbC5wcm90by5zZXJ2aWNlcy5jb250ZXN0YW50QhNDbG91ZEZvcm1hdGlvblByb3RvUAFaSWdpdGh1Yi5jb20vaXN1Y29uL2lzdWNvbjE0LXBvcnRhbC9wcm90by5nby9pc3V4cG9ydGFsL3NlcnZpY2VzL2NvbnRlc3RhbnSiAgRJUFNDqgIkSXN1eHBvcnRhbC5Qcm90by5TZXJ2aWNlcy5Db250ZXN0YW50ygIkSXN1eHBvcnRhbFxQcm90b1xTZXJ2aWNlc1xDb250ZXN0YW504gIwSXN1eHBvcnRhbFxQcm90b1xTZXJ2aWNlc1xDb250ZXN0YW50XEdQQk1ldGFkYXRh6gInSXN1eHBvcnRhbDo6UHJvdG86OlNlcnZpY2VzOjpDb250ZXN0YW50YgZwcm90bzM");

/**
 * Describes the message isuxportal.proto.services.contestant.GetCloudFormationQuery.
 * Use `create(GetCloudFormationQuerySchema)` to create a new message.
 */
export const GetCloudFormationQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_contestant_cloud_formation, 0);

/**
 * Describes the message isuxportal.proto.services.contestant.GetCloudFormationResponse.
 * Use `create(GetCloudFormationResponseSchema)` to create a new message.
 */
export const GetCloudFormationResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_contestant_cloud_formation, 1);

