// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/contestant/cloud_formation.proto (package isuxportal.proto.services.contestant, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file isuxportal/services/contestant/cloud_formation.proto.
 */
export declare const file_isuxportal_services_contestant_cloud_formation: GenFile;

/**
 * @generated from message isuxportal.proto.services.contestant.GetCloudFormationQuery
 */
export declare type GetCloudFormationQuery = Message<"isuxportal.proto.services.contestant.GetCloudFormationQuery"> & {
};

/**
 * Describes the message isuxportal.proto.services.contestant.GetCloudFormationQuery.
 * Use `create(GetCloudFormationQuerySchema)` to create a new message.
 */
export declare const GetCloudFormationQuerySchema: GenMessage<GetCloudFormationQuery>;

/**
 * @generated from message isuxportal.proto.services.contestant.GetCloudFormationResponse
 */
export declare type GetCloudFormationResponse = Message<"isuxportal.proto.services.contestant.GetCloudFormationResponse"> & {
  /**
   * @generated from field: string template = 1;
   */
  template: string;
};

/**
 * Describes the message isuxportal.proto.services.contestant.GetCloudFormationResponse.
 * Use `create(GetCloudFormationResponseSchema)` to create a new message.
 */
export declare const GetCloudFormationResponseSchema: GenMessage<GetCloudFormationResponse>;

