// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/contestant/dashboard.proto (package isuxportal.proto.services.contestant, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_leaderboard } from "../../resources/leaderboard_pb";

/**
 * Describes the file isuxportal/services/contestant/dashboard.proto.
 */
export const file_isuxportal_services_contestant_dashboard = /*@__PURE__*/
  fileDesc("Ci5pc3V4cG9ydGFsL3NlcnZpY2VzL2NvbnRlc3RhbnQvZGFzaGJvYXJkLnByb3RvEiRpc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLmNvbnRlc3RhbnQiEAoORGFzaGJvYXJkUXVlcnkiWgoRRGFzaGJvYXJkUmVzcG9uc2USRQoQbGVhZGVyYm9hcmRfaXRlbRgBIAEoCzIrLmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzLkxlYWRlcmJvYXJkSXRlbULKAgooY29tLmlzdXhwb3J0YWwucHJvdG8uc2VydmljZXMuY29udGVzdGFudEIORGFzaGJvYXJkUHJvdG9QAVpaZ2l0aHViLmNvbS9pc3Vjb24vaXN1Y29uMTQtcG9ydGFsL3N1cGVydmlzb3IvZHVtbXliZW5jaC9nZW4vaXN1eHBvcnRhbC9zZXJ2aWNlcy9jb250ZXN0YW50ogIESVBTQ6oCJElzdXhwb3J0YWwuUHJvdG8uU2VydmljZXMuQ29udGVzdGFudMoCJElzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcQ29udGVzdGFudOICMElzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcQ29udGVzdGFudFxHUEJNZXRhZGF0YeoCJ0lzdXhwb3J0YWw6OlByb3RvOjpTZXJ2aWNlczo6Q29udGVzdGFudGIGcHJvdG8z", [file_isuxportal_resources_leaderboard]);

/**
 * Describes the message isuxportal.proto.services.contestant.DashboardQuery.
 * Use `create(DashboardQuerySchema)` to create a new message.
 */
export const DashboardQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_contestant_dashboard, 0);

/**
 * Describes the message isuxportal.proto.services.contestant.DashboardResponse.
 * Use `create(DashboardResponseSchema)` to create a new message.
 */
export const DashboardResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_contestant_dashboard, 1);

