// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/contestant/instances.proto (package isuxportal.proto.services.contestant, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { ContestantInstance } from "../../resources/contestant_instance_pb";

/**
 * Describes the file isuxportal/services/contestant/instances.proto.
 */
export declare const file_isuxportal_services_contestant_instances: GenFile;

/**
 * @generated from message isuxportal.proto.services.contestant.ListContestantInstancesRequest
 */
export declare type ListContestantInstancesRequest = Message<"isuxportal.proto.services.contestant.ListContestantInstancesRequest"> & {
};

/**
 * Describes the message isuxportal.proto.services.contestant.ListContestantInstancesRequest.
 * Use `create(ListContestantInstancesRequestSchema)` to create a new message.
 */
export declare const ListContestantInstancesRequestSchema: GenMessage<ListContestantInstancesRequest>;

/**
 * @generated from message isuxportal.proto.services.contestant.ListContestantInstancesResponse
 */
export declare type ListContestantInstancesResponse = Message<"isuxportal.proto.services.contestant.ListContestantInstancesResponse"> & {
  /**
   * @generated from field: repeated isuxportal.proto.resources.ContestantInstance contestant_instances = 1;
   */
  contestantInstances: ContestantInstance[];
};

/**
 * Describes the message isuxportal.proto.services.contestant.ListContestantInstancesResponse.
 * Use `create(ListContestantInstancesResponseSchema)` to create a new message.
 */
export declare const ListContestantInstancesResponseSchema: GenMessage<ListContestantInstancesResponse>;

