// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/contestant/instances.proto (package isuxportal.proto.services.contestant, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_contestant_instance } from "../../resources/contestant_instance_pb";

/**
 * Describes the file isuxportal/services/contestant/instances.proto.
 */
export const file_isuxportal_services_contestant_instances = /*@__PURE__*/
  fileDesc("Ci5pc3V4cG9ydGFsL3NlcnZpY2VzL2NvbnRlc3RhbnQvaW5zdGFuY2VzLnByb3RvEiRpc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLmNvbnRlc3RhbnQiIAoeTGlzdENvbnRlc3RhbnRJbnN0YW5jZXNSZXF1ZXN0Im8KH0xpc3RDb250ZXN0YW50SW5zdGFuY2VzUmVzcG9uc2USTAoUY29udGVzdGFudF9pbnN0YW5jZXMYASADKAsyLi5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcy5Db250ZXN0YW50SW5zdGFuY2VCuQIKKGNvbS5pc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLmNvbnRlc3RhbnRCDkluc3RhbmNlc1Byb3RvUAFaSWdpdGh1Yi5jb20vaXN1Y29uL2lzdWNvbjE0LXBvcnRhbC9wcm90by5nby9pc3V4cG9ydGFsL3NlcnZpY2VzL2NvbnRlc3RhbnSiAgRJUFNDqgIkSXN1eHBvcnRhbC5Qcm90by5TZXJ2aWNlcy5Db250ZXN0YW50ygIkSXN1eHBvcnRhbFxQcm90b1xTZXJ2aWNlc1xDb250ZXN0YW504gIwSXN1eHBvcnRhbFxQcm90b1xTZXJ2aWNlc1xDb250ZXN0YW50XEdQQk1ldGFkYXRh6gInSXN1eHBvcnRhbDo6UHJvdG86OlNlcnZpY2VzOjpDb250ZXN0YW50YgZwcm90bzM", [file_isuxportal_resources_contestant_instance]);

/**
 * Describes the message isuxportal.proto.services.contestant.ListContestantInstancesRequest.
 * Use `create(ListContestantInstancesRequestSchema)` to create a new message.
 */
export const ListContestantInstancesRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_contestant_instances, 0);

/**
 * Describes the message isuxportal.proto.services.contestant.ListContestantInstancesResponse.
 * Use `create(ListContestantInstancesResponseSchema)` to create a new message.
 */
export const ListContestantInstancesResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_contestant_instances, 1);

