// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/contestant/notifications.proto (package isuxportal.proto.services.contestant, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_notification } from "../../resources/notification_pb";

/**
 * Describes the file isuxportal/services/contestant/notifications.proto.
 */
export const file_isuxportal_services_contestant_notifications = /*@__PURE__*/
  fileDesc("CjJpc3V4cG9ydGFsL3NlcnZpY2VzL2NvbnRlc3RhbnQvbm90aWZpY2F0aW9ucy5wcm90bxIkaXN1eHBvcnRhbC5wcm90by5zZXJ2aWNlcy5jb250ZXN0YW50IicKFkxpc3ROb3RpZmljYXRpb25zUXVlcnkSDQoFYWZ0ZXIYASABKAMihAEKGUxpc3ROb3RpZmljYXRpb25zUmVzcG9uc2USJgoebGFzdF9hbnN3ZXJlZF9jbGFyaWZpY2F0aW9uX2lkGAEgASgDEj8KDW5vdGlmaWNhdGlvbnMYAiADKAsyKC5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcy5Ob3RpZmljYXRpb24iTgocU3Vic2NyaWJlTm90aWZpY2F0aW9uUmVxdWVzdBIQCghlbmRwb2ludBgBIAEoCRIOCgZwMjU2ZGgYAiABKAkSDAoEYXV0aBgDIAEoCSIfCh1TdWJzY3JpYmVOb3RpZmljYXRpb25SZXNwb25zZSIyCh5VbnN1YnNjcmliZU5vdGlmaWNhdGlvblJlcXVlc3QSEAoIZW5kcG9pbnQYASABKAkiIQofVW5zdWJzY3JpYmVOb3RpZmljYXRpb25SZXNwb25zZUK9AgooY29tLmlzdXhwb3J0YWwucHJvdG8uc2VydmljZXMuY29udGVzdGFudEISTm90aWZpY2F0aW9uc1Byb3RvUAFaSWdpdGh1Yi5jb20vaXN1Y29uL2lzdWNvbjE0LXBvcnRhbC9wcm90by5nby9pc3V4cG9ydGFsL3NlcnZpY2VzL2NvbnRlc3RhbnSiAgRJUFNDqgIkSXN1eHBvcnRhbC5Qcm90by5TZXJ2aWNlcy5Db250ZXN0YW50ygIkSXN1eHBvcnRhbFxQcm90b1xTZXJ2aWNlc1xDb250ZXN0YW504gIwSXN1eHBvcnRhbFxQcm90b1xTZXJ2aWNlc1xDb250ZXN0YW50XEdQQk1ldGFkYXRh6gInSXN1eHBvcnRhbDo6UHJvdG86OlNlcnZpY2VzOjpDb250ZXN0YW50YgZwcm90bzM", [file_isuxportal_resources_notification]);

/**
 * Describes the message isuxportal.proto.services.contestant.ListNotificationsQuery.
 * Use `create(ListNotificationsQuerySchema)` to create a new message.
 */
export const ListNotificationsQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_contestant_notifications, 0);

/**
 * Describes the message isuxportal.proto.services.contestant.ListNotificationsResponse.
 * Use `create(ListNotificationsResponseSchema)` to create a new message.
 */
export const ListNotificationsResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_contestant_notifications, 1);

/**
 * Describes the message isuxportal.proto.services.contestant.SubscribeNotificationRequest.
 * Use `create(SubscribeNotificationRequestSchema)` to create a new message.
 */
export const SubscribeNotificationRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_contestant_notifications, 2);

/**
 * Describes the message isuxportal.proto.services.contestant.SubscribeNotificationResponse.
 * Use `create(SubscribeNotificationResponseSchema)` to create a new message.
 */
export const SubscribeNotificationResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_contestant_notifications, 3);

/**
 * Describes the message isuxportal.proto.services.contestant.UnsubscribeNotificationRequest.
 * Use `create(UnsubscribeNotificationRequestSchema)` to create a new message.
 */
export const UnsubscribeNotificationRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_contestant_notifications, 4);

/**
 * Describes the message isuxportal.proto.services.contestant.UnsubscribeNotificationResponse.
 * Use `create(UnsubscribeNotificationResponseSchema)` to create a new message.
 */
export const UnsubscribeNotificationResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_contestant_notifications, 5);

