// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/contestant/notifications.proto (package isuxportal.proto.services.contestant, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Notification } from "../../resources/notification_pb";

/**
 * Describes the file isuxportal/services/contestant/notifications.proto.
 */
export declare const file_isuxportal_services_contestant_notifications: GenFile;

/**
 * @generated from message isuxportal.proto.services.contestant.ListNotificationsQuery
 */
export declare type ListNotificationsQuery = Message<"isuxportal.proto.services.contestant.ListNotificationsQuery"> & {
  /**
   * Last notifications.id that a user-agent has received through ListNotificationsQuery during a current session.
   * If not specified (=0), uses server-side `read` column as a hint.
   *
   * @generated from field: int64 after = 1;
   */
  after: bigint;
};

/**
 * Describes the message isuxportal.proto.services.contestant.ListNotificationsQuery.
 * Use `create(ListNotificationsQuerySchema)` to create a new message.
 */
export declare const ListNotificationsQuerySchema: GenMessage<ListNotificationsQuery>;

/**
 * @generated from message isuxportal.proto.services.contestant.ListNotificationsResponse
 */
export declare type ListNotificationsResponse = Message<"isuxportal.proto.services.contestant.ListNotificationsResponse"> & {
  /**
   * @generated from field: int64 last_answered_clarification_id = 1;
   */
  lastAnsweredClarificationId: bigint;

  /**
   * @generated from field: repeated isuxportal.proto.resources.Notification notifications = 2;
   */
  notifications: Notification[];
};

/**
 * Describes the message isuxportal.proto.services.contestant.ListNotificationsResponse.
 * Use `create(ListNotificationsResponseSchema)` to create a new message.
 */
export declare const ListNotificationsResponseSchema: GenMessage<ListNotificationsResponse>;

/**
 * @generated from message isuxportal.proto.services.contestant.SubscribeNotificationRequest
 */
export declare type SubscribeNotificationRequest = Message<"isuxportal.proto.services.contestant.SubscribeNotificationRequest"> & {
  /**
   * @generated from field: string endpoint = 1;
   */
  endpoint: string;

  /**
   * @generated from field: string p256dh = 2;
   */
  p256dh: string;

  /**
   * @generated from field: string auth = 3;
   */
  auth: string;
};

/**
 * Describes the message isuxportal.proto.services.contestant.SubscribeNotificationRequest.
 * Use `create(SubscribeNotificationRequestSchema)` to create a new message.
 */
export declare const SubscribeNotificationRequestSchema: GenMessage<SubscribeNotificationRequest>;

/**
 * @generated from message isuxportal.proto.services.contestant.SubscribeNotificationResponse
 */
export declare type SubscribeNotificationResponse = Message<"isuxportal.proto.services.contestant.SubscribeNotificationResponse"> & {
};

/**
 * Describes the message isuxportal.proto.services.contestant.SubscribeNotificationResponse.
 * Use `create(SubscribeNotificationResponseSchema)` to create a new message.
 */
export declare const SubscribeNotificationResponseSchema: GenMessage<SubscribeNotificationResponse>;

/**
 * @generated from message isuxportal.proto.services.contestant.UnsubscribeNotificationRequest
 */
export declare type UnsubscribeNotificationRequest = Message<"isuxportal.proto.services.contestant.UnsubscribeNotificationRequest"> & {
  /**
   * @generated from field: string endpoint = 1;
   */
  endpoint: string;
};

/**
 * Describes the message isuxportal.proto.services.contestant.UnsubscribeNotificationRequest.
 * Use `create(UnsubscribeNotificationRequestSchema)` to create a new message.
 */
export declare const UnsubscribeNotificationRequestSchema: GenMessage<UnsubscribeNotificationRequest>;

/**
 * @generated from message isuxportal.proto.services.contestant.UnsubscribeNotificationResponse
 */
export declare type UnsubscribeNotificationResponse = Message<"isuxportal.proto.services.contestant.UnsubscribeNotificationResponse"> & {
};

/**
 * Describes the message isuxportal.proto.services.contestant.UnsubscribeNotificationResponse.
 * Use `create(UnsubscribeNotificationResponseSchema)` to create a new message.
 */
export declare const UnsubscribeNotificationResponseSchema: GenMessage<UnsubscribeNotificationResponse>;

