// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/admin/clarifications.proto (package isuxportal.proto.services.admin, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Clarification } from "../../resources/clarification_pb";

/**
 * Describes the file isuxportal/services/admin/clarifications.proto.
 */
export declare const file_isuxportal_services_admin_clarifications: GenFile;

/**
 * @generated from message isuxportal.proto.services.admin.ListClarificationsQuery
 */
export declare type ListClarificationsQuery = Message<"isuxportal.proto.services.admin.ListClarificationsQuery"> & {
  /**
   * optional to filter
   *
   * @generated from field: int64 team_id = 1;
   */
  teamId: bigint;

  /**
   * @generated from field: bool unanswered_only = 2;
   */
  unansweredOnly: boolean;
};

/**
 * Describes the message isuxportal.proto.services.admin.ListClarificationsQuery.
 * Use `create(ListClarificationsQuerySchema)` to create a new message.
 */
export declare const ListClarificationsQuerySchema: GenMessage<ListClarificationsQuery>;

/**
 * @generated from message isuxportal.proto.services.admin.ListClarificationsResponse
 */
export declare type ListClarificationsResponse = Message<"isuxportal.proto.services.admin.ListClarificationsResponse"> & {
  /**
   * @generated from field: repeated isuxportal.proto.resources.Clarification clarifications = 1;
   */
  clarifications: Clarification[];
};

/**
 * Describes the message isuxportal.proto.services.admin.ListClarificationsResponse.
 * Use `create(ListClarificationsResponseSchema)` to create a new message.
 */
export declare const ListClarificationsResponseSchema: GenMessage<ListClarificationsResponse>;

/**
 * @generated from message isuxportal.proto.services.admin.GetClarificationQuery
 */
export declare type GetClarificationQuery = Message<"isuxportal.proto.services.admin.GetClarificationQuery"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message isuxportal.proto.services.admin.GetClarificationQuery.
 * Use `create(GetClarificationQuerySchema)` to create a new message.
 */
export declare const GetClarificationQuerySchema: GenMessage<GetClarificationQuery>;

/**
 * @generated from message isuxportal.proto.services.admin.GetClarificationResponse
 */
export declare type GetClarificationResponse = Message<"isuxportal.proto.services.admin.GetClarificationResponse"> & {
  /**
   * @generated from field: isuxportal.proto.resources.Clarification clarification = 1;
   */
  clarification?: Clarification;
};

/**
 * Describes the message isuxportal.proto.services.admin.GetClarificationResponse.
 * Use `create(GetClarificationResponseSchema)` to create a new message.
 */
export declare const GetClarificationResponseSchema: GenMessage<GetClarificationResponse>;

/**
 * @generated from message isuxportal.proto.services.admin.RespondClarificationRequest
 */
export declare type RespondClarificationRequest = Message<"isuxportal.proto.services.admin.RespondClarificationRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: bool disclose = 2;
   */
  disclose: boolean;

  /**
   * @generated from field: string answer = 3;
   */
  answer: string;

  /**
   * optional to override original question
   *
   * @generated from field: string question = 4;
   */
  question: string;
};

/**
 * Describes the message isuxportal.proto.services.admin.RespondClarificationRequest.
 * Use `create(RespondClarificationRequestSchema)` to create a new message.
 */
export declare const RespondClarificationRequestSchema: GenMessage<RespondClarificationRequest>;

/**
 * @generated from message isuxportal.proto.services.admin.RespondClarificationResponse
 */
export declare type RespondClarificationResponse = Message<"isuxportal.proto.services.admin.RespondClarificationResponse"> & {
  /**
   * @generated from field: isuxportal.proto.resources.Clarification clarification = 1;
   */
  clarification?: Clarification;
};

/**
 * Describes the message isuxportal.proto.services.admin.RespondClarificationResponse.
 * Use `create(RespondClarificationResponseSchema)` to create a new message.
 */
export declare const RespondClarificationResponseSchema: GenMessage<RespondClarificationResponse>;

/**
 * @generated from message isuxportal.proto.services.admin.CreateClarificationRequest
 */
export declare type CreateClarificationRequest = Message<"isuxportal.proto.services.admin.CreateClarificationRequest"> & {
  /**
   * @generated from field: string answer = 2;
   */
  answer: string;

  /**
   * @generated from field: string question = 3;
   */
  question: string;

  /**
   * @generated from field: int64 team_id = 4;
   */
  teamId: bigint;
};

/**
 * Describes the message isuxportal.proto.services.admin.CreateClarificationRequest.
 * Use `create(CreateClarificationRequestSchema)` to create a new message.
 */
export declare const CreateClarificationRequestSchema: GenMessage<CreateClarificationRequest>;

/**
 * @generated from message isuxportal.proto.services.admin.CreateClarificationResponse
 */
export declare type CreateClarificationResponse = Message<"isuxportal.proto.services.admin.CreateClarificationResponse"> & {
  /**
   * @generated from field: isuxportal.proto.resources.Clarification clarification = 1;
   */
  clarification?: Clarification;
};

/**
 * Describes the message isuxportal.proto.services.admin.CreateClarificationResponse.
 * Use `create(CreateClarificationResponseSchema)` to create a new message.
 */
export declare const CreateClarificationResponseSchema: GenMessage<CreateClarificationResponse>;

