// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/admin/clarifications.proto (package isuxportal.proto.services.admin, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_clarification } from "../../resources/clarification_pb";

/**
 * Describes the file isuxportal/services/admin/clarifications.proto.
 */
export const file_isuxportal_services_admin_clarifications = /*@__PURE__*/
  fileDesc("Ci5pc3V4cG9ydGFsL3NlcnZpY2VzL2FkbWluL2NsYXJpZmljYXRpb25zLnByb3RvEh9pc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLmFkbWluIkMKF0xpc3RDbGFyaWZpY2F0aW9uc1F1ZXJ5Eg8KB3RlYW1faWQYASABKAMSFwoPdW5hbnN3ZXJlZF9vbmx5GAIgASgIIl8KGkxpc3RDbGFyaWZpY2F0aW9uc1Jlc3BvbnNlEkEKDmNsYXJpZmljYXRpb25zGAEgAygLMikuaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMuQ2xhcmlmaWNhdGlvbiIjChVHZXRDbGFyaWZpY2F0aW9uUXVlcnkSCgoCaWQYASABKAMiXAoYR2V0Q2xhcmlmaWNhdGlvblJlc3BvbnNlEkAKDWNsYXJpZmljYXRpb24YASABKAsyKS5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcy5DbGFyaWZpY2F0aW9uIl0KG1Jlc3BvbmRDbGFyaWZpY2F0aW9uUmVxdWVzdBIKCgJpZBgBIAEoAxIQCghkaXNjbG9zZRgCIAEoCBIOCgZhbnN3ZXIYAyABKAkSEAoIcXVlc3Rpb24YBCABKAkiYAocUmVzcG9uZENsYXJpZmljYXRpb25SZXNwb25zZRJACg1jbGFyaWZpY2F0aW9uGAEgASgLMikuaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMuQ2xhcmlmaWNhdGlvbiJPChpDcmVhdGVDbGFyaWZpY2F0aW9uUmVxdWVzdBIOCgZhbnN3ZXIYAiABKAkSEAoIcXVlc3Rpb24YAyABKAkSDwoHdGVhbV9pZBgEIAEoAyJfChtDcmVhdGVDbGFyaWZpY2F0aW9uUmVzcG9uc2USQAoNY2xhcmlmaWNhdGlvbhgBIAEoCzIpLmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzLkNsYXJpZmljYXRpb25CsQIKI2NvbS5pc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLmFkbWluQhNDbGFyaWZpY2F0aW9uc1Byb3RvUAFaVWdpdGh1Yi5jb20vaXN1Y29uL2lzdWNvbjE0LXBvcnRhbC9zdXBlcnZpc29yL2R1bW15YmVuY2gvZ2VuL2lzdXhwb3J0YWwvc2VydmljZXMvYWRtaW6iAgRJUFNBqgIfSXN1eHBvcnRhbC5Qcm90by5TZXJ2aWNlcy5BZG1pbsoCH0lzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcQWRtaW7iAitJc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXEFkbWluXEdQQk1ldGFkYXRh6gIiSXN1eHBvcnRhbDo6UHJvdG86OlNlcnZpY2VzOjpBZG1pbmIGcHJvdG8z", [file_isuxportal_resources_clarification]);

/**
 * Describes the message isuxportal.proto.services.admin.ListClarificationsQuery.
 * Use `create(ListClarificationsQuerySchema)` to create a new message.
 */
export const ListClarificationsQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_clarifications, 0);

/**
 * Describes the message isuxportal.proto.services.admin.ListClarificationsResponse.
 * Use `create(ListClarificationsResponseSchema)` to create a new message.
 */
export const ListClarificationsResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_clarifications, 1);

/**
 * Describes the message isuxportal.proto.services.admin.GetClarificationQuery.
 * Use `create(GetClarificationQuerySchema)` to create a new message.
 */
export const GetClarificationQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_clarifications, 2);

/**
 * Describes the message isuxportal.proto.services.admin.GetClarificationResponse.
 * Use `create(GetClarificationResponseSchema)` to create a new message.
 */
export const GetClarificationResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_clarifications, 3);

/**
 * Describes the message isuxportal.proto.services.admin.RespondClarificationRequest.
 * Use `create(RespondClarificationRequestSchema)` to create a new message.
 */
export const RespondClarificationRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_clarifications, 4);

/**
 * Describes the message isuxportal.proto.services.admin.RespondClarificationResponse.
 * Use `create(RespondClarificationResponseSchema)` to create a new message.
 */
export const RespondClarificationResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_clarifications, 5);

/**
 * Describes the message isuxportal.proto.services.admin.CreateClarificationRequest.
 * Use `create(CreateClarificationRequestSchema)` to create a new message.
 */
export const CreateClarificationRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_clarifications, 6);

/**
 * Describes the message isuxportal.proto.services.admin.CreateClarificationResponse.
 * Use `create(CreateClarificationResponseSchema)` to create a new message.
 */
export const CreateClarificationResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_clarifications, 7);

