// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/admin/cloud_formation.proto (package isuxportal.proto.services.admin, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/services/admin/cloud_formation.proto.
 */
export const file_isuxportal_services_admin_cloud_formation = /*@__PURE__*/
  fileDesc("Ci9pc3V4cG9ydGFsL3NlcnZpY2VzL2FkbWluL2Nsb3VkX2Zvcm1hdGlvbi5wcm90bxIfaXN1eHBvcnRhbC5wcm90by5zZXJ2aWNlcy5hZG1pbiIyChZHZXRDbG91ZEZvcm1hdGlvblF1ZXJ5EgoKAmlkGAEgASgDEgwKBHR5cGUYAiABKAkiLQoZR2V0Q2xvdWRGb3JtYXRpb25SZXNwb25zZRIQCgh0ZW1wbGF0ZRgBIAEoCUKxAgojY29tLmlzdXhwb3J0YWwucHJvdG8uc2VydmljZXMuYWRtaW5CE0Nsb3VkRm9ybWF0aW9uUHJvdG9QAVpVZ2l0aHViLmNvbS9pc3Vjb24vaXN1Y29uMTQtcG9ydGFsL3N1cGVydmlzb3IvZHVtbXliZW5jaC9nZW4vaXN1eHBvcnRhbC9zZXJ2aWNlcy9hZG1pbqICBElQU0GqAh9Jc3V4cG9ydGFsLlByb3RvLlNlcnZpY2VzLkFkbWluygIfSXN1eHBvcnRhbFxQcm90b1xTZXJ2aWNlc1xBZG1pbuICK0lzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcQWRtaW5cR1BCTWV0YWRhdGHqAiJJc3V4cG9ydGFsOjpQcm90bzo6U2VydmljZXM6OkFkbWluYgZwcm90bzM");

/**
 * Describes the message isuxportal.proto.services.admin.GetCloudFormationQuery.
 * Use `create(GetCloudFormationQuerySchema)` to create a new message.
 */
export const GetCloudFormationQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_cloud_formation, 0);

/**
 * Describes the message isuxportal.proto.services.admin.GetCloudFormationResponse.
 * Use `create(GetCloudFormationResponseSchema)` to create a new message.
 */
export const GetCloudFormationResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_cloud_formation, 1);

