// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/admin/cloud_formation.proto (package isuxportal.proto.services.admin, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file isuxportal/services/admin/cloud_formation.proto.
 */
export declare const file_isuxportal_services_admin_cloud_formation: GenFile;

/**
 * @generated from message isuxportal.proto.services.admin.GetCloudFormationQuery
 */
export declare type GetCloudFormationQuery = Message<"isuxportal.proto.services.admin.GetCloudFormationQuery"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * query parameter. "test" | "qualify"
   *
   * @generated from field: string type = 2;
   */
  type: string;
};

/**
 * Describes the message isuxportal.proto.services.admin.GetCloudFormationQuery.
 * Use `create(GetCloudFormationQuerySchema)` to create a new message.
 */
export declare const GetCloudFormationQuerySchema: GenMessage<GetCloudFormationQuery>;

/**
 * @generated from message isuxportal.proto.services.admin.GetCloudFormationResponse
 */
export declare type GetCloudFormationResponse = Message<"isuxportal.proto.services.admin.GetCloudFormationResponse"> & {
  /**
   * @generated from field: string template = 1;
   */
  template: string;
};

/**
 * Describes the message isuxportal.proto.services.admin.GetCloudFormationResponse.
 * Use `create(GetCloudFormationResponseSchema)` to create a new message.
 */
export declare const GetCloudFormationResponseSchema: GenMessage<GetCloudFormationResponse>;

