// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/admin/contestant_instances.proto (package isuxportal.proto.services.admin, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { ContestantInstance } from "../../resources/contestant_instance_pb";

/**
 * Describes the file isuxportal/services/admin/contestant_instances.proto.
 */
export declare const file_isuxportal_services_admin_contestant_instances: GenFile;

/**
 * @generated from message isuxportal.proto.services.admin.ListContestantInstancesQuery
 */
export declare type ListContestantInstancesQuery = Message<"isuxportal.proto.services.admin.ListContestantInstancesQuery"> & {
  /**
   * optional filter by team_id
   *
   * @generated from field: int64 team_id = 1;
   */
  teamId: bigint;
};

/**
 * Describes the message isuxportal.proto.services.admin.ListContestantInstancesQuery.
 * Use `create(ListContestantInstancesQuerySchema)` to create a new message.
 */
export declare const ListContestantInstancesQuerySchema: GenMessage<ListContestantInstancesQuery>;

/**
 * @generated from message isuxportal.proto.services.admin.ListContestantInstancesResponse
 */
export declare type ListContestantInstancesResponse = Message<"isuxportal.proto.services.admin.ListContestantInstancesResponse"> & {
  /**
   * @generated from field: repeated isuxportal.proto.resources.ContestantInstance contestant_instances = 1;
   */
  contestantInstances: ContestantInstance[];
};

/**
 * Describes the message isuxportal.proto.services.admin.ListContestantInstancesResponse.
 * Use `create(ListContestantInstancesResponseSchema)` to create a new message.
 */
export declare const ListContestantInstancesResponseSchema: GenMessage<ListContestantInstancesResponse>;

