// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/admin/contestant_instances.proto (package isuxportal.proto.services.admin, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_contestant_instance } from "../../resources/contestant_instance_pb";

/**
 * Describes the file isuxportal/services/admin/contestant_instances.proto.
 */
export const file_isuxportal_services_admin_contestant_instances = /*@__PURE__*/
  fileDesc("CjRpc3V4cG9ydGFsL3NlcnZpY2VzL2FkbWluL2NvbnRlc3RhbnRfaW5zdGFuY2VzLnByb3RvEh9pc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLmFkbWluIi8KHExpc3RDb250ZXN0YW50SW5zdGFuY2VzUXVlcnkSDwoHdGVhbV9pZBgBIAEoAyJvCh9MaXN0Q29udGVzdGFudEluc3RhbmNlc1Jlc3BvbnNlEkwKFGNvbnRlc3RhbnRfaW5zdGFuY2VzGAEgAygLMi4uaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMuQ29udGVzdGFudEluc3RhbmNlQqUCCiNjb20uaXN1eHBvcnRhbC5wcm90by5zZXJ2aWNlcy5hZG1pbkIYQ29udGVzdGFudEluc3RhbmNlc1Byb3RvUAFaRGdpdGh1Yi5jb20vaXN1Y29uL2lzdWNvbjE0LXBvcnRhbC9wcm90by5nby9pc3V4cG9ydGFsL3NlcnZpY2VzL2FkbWluogIESVBTQaoCH0lzdXhwb3J0YWwuUHJvdG8uU2VydmljZXMuQWRtaW7KAh9Jc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXEFkbWlu4gIrSXN1eHBvcnRhbFxQcm90b1xTZXJ2aWNlc1xBZG1pblxHUEJNZXRhZGF0YeoCIklzdXhwb3J0YWw6OlByb3RvOjpTZXJ2aWNlczo6QWRtaW5iBnByb3RvMw", [file_isuxportal_resources_contestant_instance]);

/**
 * Describes the message isuxportal.proto.services.admin.ListContestantInstancesQuery.
 * Use `create(ListContestantInstancesQuerySchema)` to create a new message.
 */
export const ListContestantInstancesQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_contestant_instances, 0);

/**
 * Describes the message isuxportal.proto.services.admin.ListContestantInstancesResponse.
 * Use `create(ListContestantInstancesResponseSchema)` to create a new message.
 */
export const ListContestantInstancesResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_contestant_instances, 1);

