// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/admin/contestant_instances.proto (package isuxportal.proto.services.admin, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_contestant_instance } from "../../resources/contestant_instance_pb";

/**
 * Describes the file isuxportal/services/admin/contestant_instances.proto.
 */
export const file_isuxportal_services_admin_contestant_instances = /*@__PURE__*/
  fileDesc("CjRpc3V4cG9ydGFsL3NlcnZpY2VzL2FkbWluL2NvbnRlc3RhbnRfaW5zdGFuY2VzLnByb3RvEh9pc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLmFkbWluIi8KHExpc3RDb250ZXN0YW50SW5zdGFuY2VzUXVlcnkSDwoHdGVhbV9pZBgBIAEoAyJvCh9MaXN0Q29udGVzdGFudEluc3RhbmNlc1Jlc3BvbnNlEkwKFGNvbnRlc3RhbnRfaW5zdGFuY2VzGAEgAygLMi4uaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMuQ29udGVzdGFudEluc3RhbmNlQrYCCiNjb20uaXN1eHBvcnRhbC5wcm90by5zZXJ2aWNlcy5hZG1pbkIYQ29udGVzdGFudEluc3RhbmNlc1Byb3RvUAFaVWdpdGh1Yi5jb20vaXN1Y29uL2lzdWNvbjE0LXBvcnRhbC9zdXBlcnZpc29yL2R1bW15YmVuY2gvZ2VuL2lzdXhwb3J0YWwvc2VydmljZXMvYWRtaW6iAgRJUFNBqgIfSXN1eHBvcnRhbC5Qcm90by5TZXJ2aWNlcy5BZG1pbsoCH0lzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcQWRtaW7iAitJc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXEFkbWluXEdQQk1ldGFkYXRh6gIiSXN1eHBvcnRhbDo6UHJvdG86OlNlcnZpY2VzOjpBZG1pbmIGcHJvdG8z", [file_isuxportal_resources_contestant_instance]);

/**
 * Describes the message isuxportal.proto.services.admin.ListContestantInstancesQuery.
 * Use `create(ListContestantInstancesQuerySchema)` to create a new message.
 */
export const ListContestantInstancesQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_contestant_instances, 0);

/**
 * Describes the message isuxportal.proto.services.admin.ListContestantInstancesResponse.
 * Use `create(ListContestantInstancesResponseSchema)` to create a new message.
 */
export const ListContestantInstancesResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_contestant_instances, 1);

