// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/admin/dashboard.proto (package isuxportal.proto.services.admin, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Leaderboard, LeaderboardItem } from "../../resources/leaderboard_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file isuxportal/services/admin/dashboard.proto.
 */
export declare const file_isuxportal_services_admin_dashboard: GenFile;

/**
 * @generated from message isuxportal.proto.services.admin.DashboardQuery
 */
export declare type DashboardQuery = Message<"isuxportal.proto.services.admin.DashboardQuery"> & {
};

/**
 * Describes the message isuxportal.proto.services.admin.DashboardQuery.
 * Use `create(DashboardQuerySchema)` to create a new message.
 */
export declare const DashboardQuerySchema: GenMessage<DashboardQuery>;

/**
 * @generated from message isuxportal.proto.services.admin.DashboardResponse
 */
export declare type DashboardResponse = Message<"isuxportal.proto.services.admin.DashboardResponse"> & {
  /**
   * @generated from field: isuxportal.proto.resources.Leaderboard leaderboard = 1;
   */
  leaderboard?: Leaderboard;

  /**
   * @generated from field: google.protobuf.Timestamp earliest_unanswered_clarification_at = 2;
   */
  earliestUnansweredClarificationAt?: Timestamp;

  /**
   * @generated from field: int64 unanswered_clarification_count = 3;
   */
  unansweredClarificationCount: bigint;
};

/**
 * Describes the message isuxportal.proto.services.admin.DashboardResponse.
 * Use `create(DashboardResponseSchema)` to create a new message.
 */
export declare const DashboardResponseSchema: GenMessage<DashboardResponse>;

/**
 * @generated from message isuxportal.proto.services.admin.SoloDashboardQuery
 */
export declare type SoloDashboardQuery = Message<"isuxportal.proto.services.admin.SoloDashboardQuery"> & {
};

/**
 * Describes the message isuxportal.proto.services.admin.SoloDashboardQuery.
 * Use `create(SoloDashboardQuerySchema)` to create a new message.
 */
export declare const SoloDashboardQuerySchema: GenMessage<SoloDashboardQuery>;

/**
 * @generated from message isuxportal.proto.services.admin.SoloDashboardResponse
 */
export declare type SoloDashboardResponse = Message<"isuxportal.proto.services.admin.SoloDashboardResponse"> & {
  /**
   * @generated from field: isuxportal.proto.resources.LeaderboardItem leaderboard_item = 1;
   */
  leaderboardItem?: LeaderboardItem;
};

/**
 * Describes the message isuxportal.proto.services.admin.SoloDashboardResponse.
 * Use `create(SoloDashboardResponseSchema)` to create a new message.
 */
export declare const SoloDashboardResponseSchema: GenMessage<SoloDashboardResponse>;

