// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/admin/dashboard.proto (package isuxportal.proto.services.admin, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_leaderboard } from "../../resources/leaderboard_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file isuxportal/services/admin/dashboard.proto.
 */
export const file_isuxportal_services_admin_dashboard = /*@__PURE__*/
  fileDesc("Cilpc3V4cG9ydGFsL3NlcnZpY2VzL2FkbWluL2Rhc2hib2FyZC5wcm90bxIfaXN1eHBvcnRhbC5wcm90by5zZXJ2aWNlcy5hZG1pbiIQCg5EYXNoYm9hcmRRdWVyeSLDAQoRRGFzaGJvYXJkUmVzcG9uc2USPAoLbGVhZGVyYm9hcmQYASABKAsyJy5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcy5MZWFkZXJib2FyZBJICiRlYXJsaWVzdF91bmFuc3dlcmVkX2NsYXJpZmljYXRpb25fYXQYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEiYKHnVuYW5zd2VyZWRfY2xhcmlmaWNhdGlvbl9jb3VudBgDIAEoAyIUChJTb2xvRGFzaGJvYXJkUXVlcnkiXgoVU29sb0Rhc2hib2FyZFJlc3BvbnNlEkUKEGxlYWRlcmJvYXJkX2l0ZW0YASABKAsyKy5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcy5MZWFkZXJib2FyZEl0ZW1CrAIKI2NvbS5pc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLmFkbWluQg5EYXNoYm9hcmRQcm90b1ABWlVnaXRodWIuY29tL2lzdWNvbi9pc3Vjb24xNC1wb3J0YWwvc3VwZXJ2aXNvci9kdW1teWJlbmNoL2dlbi9pc3V4cG9ydGFsL3NlcnZpY2VzL2FkbWluogIESVBTQaoCH0lzdXhwb3J0YWwuUHJvdG8uU2VydmljZXMuQWRtaW7KAh9Jc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXEFkbWlu4gIrSXN1eHBvcnRhbFxQcm90b1xTZXJ2aWNlc1xBZG1pblxHUEJNZXRhZGF0YeoCIklzdXhwb3J0YWw6OlByb3RvOjpTZXJ2aWNlczo6QWRtaW5iBnByb3RvMw", [file_isuxportal_resources_leaderboard, file_google_protobuf_timestamp]);

/**
 * Describes the message isuxportal.proto.services.admin.DashboardQuery.
 * Use `create(DashboardQuerySchema)` to create a new message.
 */
export const DashboardQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_dashboard, 0);

/**
 * Describes the message isuxportal.proto.services.admin.DashboardResponse.
 * Use `create(DashboardResponseSchema)` to create a new message.
 */
export const DashboardResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_dashboard, 1);

/**
 * Describes the message isuxportal.proto.services.admin.SoloDashboardQuery.
 * Use `create(SoloDashboardQuerySchema)` to create a new message.
 */
export const SoloDashboardQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_dashboard, 2);

/**
 * Describes the message isuxportal.proto.services.admin.SoloDashboardResponse.
 * Use `create(SoloDashboardResponseSchema)` to create a new message.
 */
export const SoloDashboardResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_dashboard, 3);

