// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/admin/env_checks.proto (package isuxportal.proto.services.admin, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_env_check } from "../../resources/env_check_pb";

/**
 * Describes the file isuxportal/services/admin/env_checks.proto.
 */
export const file_isuxportal_services_admin_env_checks = /*@__PURE__*/
  fileDesc("Cippc3V4cG9ydGFsL3NlcnZpY2VzL2FkbWluL2Vudl9jaGVja3MucHJvdG8SH2lzdXhwb3J0YWwucHJvdG8uc2VydmljZXMuYWRtaW4iJQoSTGlzdEVudkNoZWNrc1F1ZXJ5Eg8KB3RlYW1faWQYASABKAMiUQoVTGlzdEVudkNoZWNrc1Jlc3BvbnNlEjgKCmVudl9jaGVja3MYASADKAsyJC5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcy5FbnZDaGVja0KsAgojY29tLmlzdXhwb3J0YWwucHJvdG8uc2VydmljZXMuYWRtaW5CDkVudkNoZWNrc1Byb3RvUAFaVWdpdGh1Yi5jb20vaXN1Y29uL2lzdWNvbjE0LXBvcnRhbC9zdXBlcnZpc29yL2R1bW15YmVuY2gvZ2VuL2lzdXhwb3J0YWwvc2VydmljZXMvYWRtaW6iAgRJUFNBqgIfSXN1eHBvcnRhbC5Qcm90by5TZXJ2aWNlcy5BZG1pbsoCH0lzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcQWRtaW7iAitJc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXEFkbWluXEdQQk1ldGFkYXRh6gIiSXN1eHBvcnRhbDo6UHJvdG86OlNlcnZpY2VzOjpBZG1pbmIGcHJvdG8z", [file_isuxportal_resources_env_check]);

/**
 * Describes the message isuxportal.proto.services.admin.ListEnvChecksQuery.
 * Use `create(ListEnvChecksQuerySchema)` to create a new message.
 */
export const ListEnvChecksQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_env_checks, 0);

/**
 * Describes the message isuxportal.proto.services.admin.ListEnvChecksResponse.
 * Use `create(ListEnvChecksResponseSchema)` to create a new message.
 */
export const ListEnvChecksResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_env_checks, 1);

