// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/admin/last_validations.proto (package isuxportal.proto.services.admin, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/services/admin/last_validations.proto.
 */
export const file_isuxportal_services_admin_last_validations = /*@__PURE__*/
  fileDesc("CjBpc3V4cG9ydGFsL3NlcnZpY2VzL2FkbWluL2xhc3RfdmFsaWRhdGlvbnMucHJvdG8SH2lzdXhwb3J0YWwucHJvdG8uc2VydmljZXMuYWRtaW4iGAoWVHJpZ2dlckVudkNoZWNrUmVxdWVzdCIZChdUcmlnZ2VyRW52Q2hlY2tSZXNwb25zZUKyAgojY29tLmlzdXhwb3J0YWwucHJvdG8uc2VydmljZXMuYWRtaW5CFExhc3RWYWxpZGF0aW9uc1Byb3RvUAFaVWdpdGh1Yi5jb20vaXN1Y29uL2lzdWNvbjE0LXBvcnRhbC9zdXBlcnZpc29yL2R1bW15YmVuY2gvZ2VuL2lzdXhwb3J0YWwvc2VydmljZXMvYWRtaW6iAgRJUFNBqgIfSXN1eHBvcnRhbC5Qcm90by5TZXJ2aWNlcy5BZG1pbsoCH0lzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcQWRtaW7iAitJc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXEFkbWluXEdQQk1ldGFkYXRh6gIiSXN1eHBvcnRhbDo6UHJvdG86OlNlcnZpY2VzOjpBZG1pbmIGcHJvdG8z");

/**
 * Describes the message isuxportal.proto.services.admin.TriggerEnvCheckRequest.
 * Use `create(TriggerEnvCheckRequestSchema)` to create a new message.
 */
export const TriggerEnvCheckRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_last_validations, 0);

/**
 * Describes the message isuxportal.proto.services.admin.TriggerEnvCheckResponse.
 * Use `create(TriggerEnvCheckResponseSchema)` to create a new message.
 */
export const TriggerEnvCheckResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_last_validations, 1);

