// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/admin/last_validations.proto (package isuxportal.proto.services.admin, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file isuxportal/services/admin/last_validations.proto.
 */
export declare const file_isuxportal_services_admin_last_validations: GenFile;

/**
 * limit to top-N teams (filter student teams?)
 *
 * @generated from message isuxportal.proto.services.admin.TriggerEnvCheckRequest
 */
export declare type TriggerEnvCheckRequest = Message<"isuxportal.proto.services.admin.TriggerEnvCheckRequest"> & {
};

/**
 * Describes the message isuxportal.proto.services.admin.TriggerEnvCheckRequest.
 * Use `create(TriggerEnvCheckRequestSchema)` to create a new message.
 */
export declare const TriggerEnvCheckRequestSchema: GenMessage<TriggerEnvCheckRequest>;

/**
 * @generated from message isuxportal.proto.services.admin.TriggerEnvCheckResponse
 */
export declare type TriggerEnvCheckResponse = Message<"isuxportal.proto.services.admin.TriggerEnvCheckResponse"> & {
};

/**
 * Describes the message isuxportal.proto.services.admin.TriggerEnvCheckResponse.
 * Use `create(TriggerEnvCheckResponseSchema)` to create a new message.
 */
export declare const TriggerEnvCheckResponseSchema: GenMessage<TriggerEnvCheckResponse>;

