// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/admin/last_validations.proto (package isuxportal.proto.services.admin, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file isuxportal/services/admin/last_validations.proto.
 */
export const file_isuxportal_services_admin_last_validations = /*@__PURE__*/
  fileDesc("CjBpc3V4cG9ydGFsL3NlcnZpY2VzL2FkbWluL2xhc3RfdmFsaWRhdGlvbnMucHJvdG8SH2lzdXhwb3J0YWwucHJvdG8uc2VydmljZXMuYWRtaW4iGAoWVHJpZ2dlckVudkNoZWNrUmVxdWVzdCIZChdUcmlnZ2VyRW52Q2hlY2tSZXNwb25zZSIfCh1UcmlnZ2VySW5zdGFuY2VSZXN0YXJ0UmVxdWVzdCIgCh5UcmlnZ2VySW5zdGFuY2VSZXN0YXJ0UmVzcG9uc2VCsgIKI2NvbS5pc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLmFkbWluQhRMYXN0VmFsaWRhdGlvbnNQcm90b1ABWlVnaXRodWIuY29tL2lzdWNvbi9pc3Vjb24xNC1wb3J0YWwvc3VwZXJ2aXNvci9kdW1teWJlbmNoL2dlbi9pc3V4cG9ydGFsL3NlcnZpY2VzL2FkbWluogIESVBTQaoCH0lzdXhwb3J0YWwuUHJvdG8uU2VydmljZXMuQWRtaW7KAh9Jc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXEFkbWlu4gIrSXN1eHBvcnRhbFxQcm90b1xTZXJ2aWNlc1xBZG1pblxHUEJNZXRhZGF0YeoCIklzdXhwb3J0YWw6OlByb3RvOjpTZXJ2aWNlczo6QWRtaW5iBnByb3RvMw");

/**
 * Describes the message isuxportal.proto.services.admin.TriggerEnvCheckRequest.
 * Use `create(TriggerEnvCheckRequestSchema)` to create a new message.
 */
export const TriggerEnvCheckRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_last_validations, 0);

/**
 * Describes the message isuxportal.proto.services.admin.TriggerEnvCheckResponse.
 * Use `create(TriggerEnvCheckResponseSchema)` to create a new message.
 */
export const TriggerEnvCheckResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_last_validations, 1);

/**
 * Describes the message isuxportal.proto.services.admin.TriggerInstanceRestartRequest.
 * Use `create(TriggerInstanceRestartRequestSchema)` to create a new message.
 */
export const TriggerInstanceRestartRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_last_validations, 2);

/**
 * Describes the message isuxportal.proto.services.admin.TriggerInstanceRestartResponse.
 * Use `create(TriggerInstanceRestartResponseSchema)` to create a new message.
 */
export const TriggerInstanceRestartResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_last_validations, 3);

