// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/admin/last_validations.proto (package isuxportal.proto.services.admin, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_instance_command_execute_request } from "../../resources/instance_command_execute_request_pb";

/**
 * Describes the file isuxportal/services/admin/last_validations.proto.
 */
export const file_isuxportal_services_admin_last_validations = /*@__PURE__*/
  fileDesc("CjBpc3V4cG9ydGFsL3NlcnZpY2VzL2FkbWluL2xhc3RfdmFsaWRhdGlvbnMucHJvdG8SH2lzdXhwb3J0YWwucHJvdG8uc2VydmljZXMuYWRtaW4iGAoWVHJpZ2dlckVudkNoZWNrUmVxdWVzdCIZChdUcmlnZ2VyRW52Q2hlY2tSZXNwb25zZSIfCh1UcmlnZ2VySW5zdGFuY2VSZXN0YXJ0UmVxdWVzdCIgCh5UcmlnZ2VySW5zdGFuY2VSZXN0YXJ0UmVzcG9uc2UiKwopTGlzdEluc3RhbmNlQ29tbWFuZEV4ZWN1dGVSZXF1ZXN0c1JlcXVlc3QieQoqTGlzdEluc3RhbmNlQ29tbWFuZEV4ZWN1dGVSZXF1ZXN0c1Jlc3BvbnNlEksKCHJlcXVlc3RzGAEgAygLMjkuaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMuSW5zdGFuY2VDb21tYW5kRXhlY3V0ZVJlcXVlc3QiNQonR2V0SW5zdGFuY2VDb21tYW5kRXhlY3V0ZVJlcXVlc3RSZXF1ZXN0EgoKAmlkGAEgASgDInwKKEdldEluc3RhbmNlQ29tbWFuZEV4ZWN1dGVSZXF1ZXN0UmVzcG9uc2USUAoHcmVzdWx0cxgBIAMoCzI/LmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzLkluc3RhbmNlQ29tbWFuZEV4ZWN1dGVSZXF1ZXN0UmVzdWx0IjsKLUdldEluc3RhbmNlQ29tbWFuZEV4ZWN1dGVSZXF1ZXN0T3V0cHV0UmVxdWVzdBIKCgJpZBgBIAEoAyJACi5HZXRJbnN0YW5jZUNvbW1hbmRFeGVjdXRlUmVxdWVzdE91dHB1dFJlc3BvbnNlEg4KBm91dHB1dBgBIAEoCUKyAgojY29tLmlzdXhwb3J0YWwucHJvdG8uc2VydmljZXMuYWRtaW5CFExhc3RWYWxpZGF0aW9uc1Byb3RvUAFaVWdpdGh1Yi5jb20vaXN1Y29uL2lzdWNvbjE0LXBvcnRhbC9zdXBlcnZpc29yL2R1bW15YmVuY2gvZ2VuL2lzdXhwb3J0YWwvc2VydmljZXMvYWRtaW6iAgRJUFNBqgIfSXN1eHBvcnRhbC5Qcm90by5TZXJ2aWNlcy5BZG1pbsoCH0lzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcQWRtaW7iAitJc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXEFkbWluXEdQQk1ldGFkYXRh6gIiSXN1eHBvcnRhbDo6UHJvdG86OlNlcnZpY2VzOjpBZG1pbmIGcHJvdG8z", [file_isuxportal_resources_instance_command_execute_request]);

/**
 * Describes the message isuxportal.proto.services.admin.TriggerEnvCheckRequest.
 * Use `create(TriggerEnvCheckRequestSchema)` to create a new message.
 */
export const TriggerEnvCheckRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_last_validations, 0);

/**
 * Describes the message isuxportal.proto.services.admin.TriggerEnvCheckResponse.
 * Use `create(TriggerEnvCheckResponseSchema)` to create a new message.
 */
export const TriggerEnvCheckResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_last_validations, 1);

/**
 * Describes the message isuxportal.proto.services.admin.TriggerInstanceRestartRequest.
 * Use `create(TriggerInstanceRestartRequestSchema)` to create a new message.
 */
export const TriggerInstanceRestartRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_last_validations, 2);

/**
 * Describes the message isuxportal.proto.services.admin.TriggerInstanceRestartResponse.
 * Use `create(TriggerInstanceRestartResponseSchema)` to create a new message.
 */
export const TriggerInstanceRestartResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_last_validations, 3);

/**
 * Describes the message isuxportal.proto.services.admin.ListInstanceCommandExecuteRequestsRequest.
 * Use `create(ListInstanceCommandExecuteRequestsRequestSchema)` to create a new message.
 */
export const ListInstanceCommandExecuteRequestsRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_last_validations, 4);

/**
 * Describes the message isuxportal.proto.services.admin.ListInstanceCommandExecuteRequestsResponse.
 * Use `create(ListInstanceCommandExecuteRequestsResponseSchema)` to create a new message.
 */
export const ListInstanceCommandExecuteRequestsResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_last_validations, 5);

/**
 * Describes the message isuxportal.proto.services.admin.GetInstanceCommandExecuteRequestRequest.
 * Use `create(GetInstanceCommandExecuteRequestRequestSchema)` to create a new message.
 */
export const GetInstanceCommandExecuteRequestRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_last_validations, 6);

/**
 * Describes the message isuxportal.proto.services.admin.GetInstanceCommandExecuteRequestResponse.
 * Use `create(GetInstanceCommandExecuteRequestResponseSchema)` to create a new message.
 */
export const GetInstanceCommandExecuteRequestResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_last_validations, 7);

/**
 * Describes the message isuxportal.proto.services.admin.GetInstanceCommandExecuteRequestOutputRequest.
 * Use `create(GetInstanceCommandExecuteRequestOutputRequestSchema)` to create a new message.
 */
export const GetInstanceCommandExecuteRequestOutputRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_last_validations, 8);

/**
 * Describes the message isuxportal.proto.services.admin.GetInstanceCommandExecuteRequestOutputResponse.
 * Use `create(GetInstanceCommandExecuteRequestOutputResponseSchema)` to create a new message.
 */
export const GetInstanceCommandExecuteRequestOutputResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_last_validations, 9);

