// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/admin/leaderboard_dump.proto (package isuxportal.proto.services.admin, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Team } from "../../resources/team_pb";
import type { LeaderboardItem_LeaderboardScore } from "../../resources/leaderboard_pb";
import type { ContestantInstance } from "../../resources/contestant_instance_pb";

/**
 * Describes the file isuxportal/services/admin/leaderboard_dump.proto.
 */
export declare const file_isuxportal_services_admin_leaderboard_dump: GenFile;

/**
 * @generated from message isuxportal.proto.services.admin.GetLeaderboardDumpQuery
 */
export declare type GetLeaderboardDumpQuery = Message<"isuxportal.proto.services.admin.GetLeaderboardDumpQuery"> & {
  /**
   * ISO8601 or "qualify-end"
   *
   * @generated from field: string when = 1;
   */
  when: string;
};

/**
 * Describes the message isuxportal.proto.services.admin.GetLeaderboardDumpQuery.
 * Use `create(GetLeaderboardDumpQuerySchema)` to create a new message.
 */
export declare const GetLeaderboardDumpQuerySchema: GenMessage<GetLeaderboardDumpQuery>;

/**
 * @generated from message isuxportal.proto.services.admin.GetLeaderboardDumpResponse
 */
export declare type GetLeaderboardDumpResponse = Message<"isuxportal.proto.services.admin.GetLeaderboardDumpResponse"> & {
  /**
   * @generated from field: repeated isuxportal.proto.services.admin.GetLeaderboardDumpResponse.LeaderboardDumpItem items = 1;
   */
  items: GetLeaderboardDumpResponse_LeaderboardDumpItem[];
};

/**
 * Describes the message isuxportal.proto.services.admin.GetLeaderboardDumpResponse.
 * Use `create(GetLeaderboardDumpResponseSchema)` to create a new message.
 */
export declare const GetLeaderboardDumpResponseSchema: GenMessage<GetLeaderboardDumpResponse>;

/**
 * @generated from message isuxportal.proto.services.admin.GetLeaderboardDumpResponse.LeaderboardDumpItem
 */
export declare type GetLeaderboardDumpResponse_LeaderboardDumpItem = Message<"isuxportal.proto.services.admin.GetLeaderboardDumpResponse.LeaderboardDumpItem"> & {
  /**
   * @generated from field: int64 position = 1;
   */
  position: bigint;

  /**
   * @generated from field: isuxportal.proto.resources.Team team = 2;
   */
  team?: Team;

  /**
   * @generated from field: isuxportal.proto.resources.LeaderboardItem.LeaderboardScore best_score = 3;
   */
  bestScore?: LeaderboardItem_LeaderboardScore;

  /**
   * @generated from field: isuxportal.proto.resources.LeaderboardItem.LeaderboardScore latest_score = 4;
   */
  latestScore?: LeaderboardItem_LeaderboardScore;

  /**
   * @generated from field: isuxportal.proto.resources.ContestantInstance target = 5;
   */
  target?: ContestantInstance;
};

/**
 * Describes the message isuxportal.proto.services.admin.GetLeaderboardDumpResponse.LeaderboardDumpItem.
 * Use `create(GetLeaderboardDumpResponse_LeaderboardDumpItemSchema)` to create a new message.
 */
export declare const GetLeaderboardDumpResponse_LeaderboardDumpItemSchema: GenMessage<GetLeaderboardDumpResponse_LeaderboardDumpItem>;

