// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/admin/leaderboard_dump.proto (package isuxportal.proto.services.admin, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_contestant_instance } from "../../resources/contestant_instance_pb";
import { file_isuxportal_resources_leaderboard } from "../../resources/leaderboard_pb";
import { file_isuxportal_resources_team } from "../../resources/team_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file isuxportal/services/admin/leaderboard_dump.proto.
 */
export const file_isuxportal_services_admin_leaderboard_dump = /*@__PURE__*/
  fileDesc("CjBpc3V4cG9ydGFsL3NlcnZpY2VzL2FkbWluL2xlYWRlcmJvYXJkX2R1bXAucHJvdG8SH2lzdXhwb3J0YWwucHJvdG8uc2VydmljZXMuYWRtaW4iJwoXR2V0TGVhZGVyYm9hcmREdW1wUXVlcnkSDAoEd2hlbhgBIAEoCSK8AwoaR2V0TGVhZGVyYm9hcmREdW1wUmVzcG9uc2USXgoFaXRlbXMYASADKAsyTy5pc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLmFkbWluLkdldExlYWRlcmJvYXJkRHVtcFJlc3BvbnNlLkxlYWRlcmJvYXJkRHVtcEl0ZW0avQIKE0xlYWRlcmJvYXJkRHVtcEl0ZW0SEAoIcG9zaXRpb24YASABKAMSLgoEdGVhbRgCIAEoCzIgLmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzLlRlYW0SUAoKYmVzdF9zY29yZRgDIAEoCzI8LmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzLkxlYWRlcmJvYXJkSXRlbS5MZWFkZXJib2FyZFNjb3JlElIKDGxhdGVzdF9zY29yZRgEIAEoCzI8LmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzLkxlYWRlcmJvYXJkSXRlbS5MZWFkZXJib2FyZFNjb3JlEj4KBnRhcmdldBgFIAEoCzIuLmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzLkNvbnRlc3RhbnRJbnN0YW5jZUKyAgojY29tLmlzdXhwb3J0YWwucHJvdG8uc2VydmljZXMuYWRtaW5CFExlYWRlcmJvYXJkRHVtcFByb3RvUAFaVWdpdGh1Yi5jb20vaXN1Y29uL2lzdWNvbjE0LXBvcnRhbC9zdXBlcnZpc29yL2R1bW15YmVuY2gvZ2VuL2lzdXhwb3J0YWwvc2VydmljZXMvYWRtaW6iAgRJUFNBqgIfSXN1eHBvcnRhbC5Qcm90by5TZXJ2aWNlcy5BZG1pbsoCH0lzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcQWRtaW7iAitJc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXEFkbWluXEdQQk1ldGFkYXRh6gIiSXN1eHBvcnRhbDo6UHJvdG86OlNlcnZpY2VzOjpBZG1pbmIGcHJvdG8z", [file_isuxportal_resources_contestant_instance, file_isuxportal_resources_leaderboard, file_isuxportal_resources_team, file_google_protobuf_timestamp]);

/**
 * Describes the message isuxportal.proto.services.admin.GetLeaderboardDumpQuery.
 * Use `create(GetLeaderboardDumpQuerySchema)` to create a new message.
 */
export const GetLeaderboardDumpQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_leaderboard_dump, 0);

/**
 * Describes the message isuxportal.proto.services.admin.GetLeaderboardDumpResponse.
 * Use `create(GetLeaderboardDumpResponseSchema)` to create a new message.
 */
export const GetLeaderboardDumpResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_leaderboard_dump, 1);

/**
 * Describes the message isuxportal.proto.services.admin.GetLeaderboardDumpResponse.LeaderboardDumpItem.
 * Use `create(GetLeaderboardDumpResponse_LeaderboardDumpItemSchema)` to create a new message.
 */
export const GetLeaderboardDumpResponse_LeaderboardDumpItemSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_leaderboard_dump, 1, 0);

