// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/admin/teams.proto (package isuxportal.proto.services.admin, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Team } from "../../resources/team_pb";
import type { Contestant } from "../../resources/contestant_pb";

/**
 * Describes the file isuxportal/services/admin/teams.proto.
 */
export declare const file_isuxportal_services_admin_teams: GenFile;

/**
 * @generated from message isuxportal.proto.services.admin.ListTeamsQuery
 */
export declare type ListTeamsQuery = Message<"isuxportal.proto.services.admin.ListTeamsQuery"> & {
};

/**
 * Describes the message isuxportal.proto.services.admin.ListTeamsQuery.
 * Use `create(ListTeamsQuerySchema)` to create a new message.
 */
export declare const ListTeamsQuerySchema: GenMessage<ListTeamsQuery>;

/**
 * @generated from message isuxportal.proto.services.admin.ListTeamsResponse
 */
export declare type ListTeamsResponse = Message<"isuxportal.proto.services.admin.ListTeamsResponse"> & {
  /**
   * @generated from field: repeated isuxportal.proto.services.admin.ListTeamsResponse.TeamListItem teams = 1;
   */
  teams: ListTeamsResponse_TeamListItem[];
};

/**
 * Describes the message isuxportal.proto.services.admin.ListTeamsResponse.
 * Use `create(ListTeamsResponseSchema)` to create a new message.
 */
export declare const ListTeamsResponseSchema: GenMessage<ListTeamsResponse>;

/**
 * @generated from message isuxportal.proto.services.admin.ListTeamsResponse.TeamListItem
 */
export declare type ListTeamsResponse_TeamListItem = Message<"isuxportal.proto.services.admin.ListTeamsResponse.TeamListItem"> & {
  /**
   * @generated from field: int64 team_id = 1;
   */
  teamId: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: repeated string member_names = 3;
   */
  memberNames: string[];

  /**
   * @generated from field: bool final_participation = 4;
   */
  finalParticipation: boolean;

  /**
   * @generated from field: bool is_student = 5;
   */
  isStudent: boolean;

  /**
   * @generated from field: bool withdrawn = 6;
   */
  withdrawn: boolean;

  /**
   * @generated from field: bool disqualified = 7;
   */
  disqualified: boolean;

  /**
   * @generated from field: bool hidden = 8;
   */
  hidden: boolean;
};

/**
 * Describes the message isuxportal.proto.services.admin.ListTeamsResponse.TeamListItem.
 * Use `create(ListTeamsResponse_TeamListItemSchema)` to create a new message.
 */
export declare const ListTeamsResponse_TeamListItemSchema: GenMessage<ListTeamsResponse_TeamListItem>;

/**
 * @generated from message isuxportal.proto.services.admin.GetTeamQuery
 */
export declare type GetTeamQuery = Message<"isuxportal.proto.services.admin.GetTeamQuery"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message isuxportal.proto.services.admin.GetTeamQuery.
 * Use `create(GetTeamQuerySchema)` to create a new message.
 */
export declare const GetTeamQuerySchema: GenMessage<GetTeamQuery>;

/**
 * @generated from message isuxportal.proto.services.admin.GetTeamResponse
 */
export declare type GetTeamResponse = Message<"isuxportal.proto.services.admin.GetTeamResponse"> & {
  /**
   * @generated from field: isuxportal.proto.resources.Team team = 1;
   */
  team?: Team;
};

/**
 * Describes the message isuxportal.proto.services.admin.GetTeamResponse.
 * Use `create(GetTeamResponseSchema)` to create a new message.
 */
export declare const GetTeamResponseSchema: GenMessage<GetTeamResponse>;

/**
 * @generated from message isuxportal.proto.services.admin.UpdateTeamQuery
 */
export declare type UpdateTeamQuery = Message<"isuxportal.proto.services.admin.UpdateTeamQuery"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message isuxportal.proto.services.admin.UpdateTeamQuery.
 * Use `create(UpdateTeamQuerySchema)` to create a new message.
 */
export declare const UpdateTeamQuerySchema: GenMessage<UpdateTeamQuery>;

/**
 * @generated from message isuxportal.proto.services.admin.UpdateTeamRequest
 */
export declare type UpdateTeamRequest = Message<"isuxportal.proto.services.admin.UpdateTeamRequest"> & {
  /**
   * @generated from field: isuxportal.proto.resources.Team team = 1;
   */
  team?: Team;

  /**
   * Update only specified contestants
   *
   * @generated from field: repeated isuxportal.proto.resources.Contestant contestants = 2;
   */
  contestants: Contestant[];
};

/**
 * Describes the message isuxportal.proto.services.admin.UpdateTeamRequest.
 * Use `create(UpdateTeamRequestSchema)` to create a new message.
 */
export declare const UpdateTeamRequestSchema: GenMessage<UpdateTeamRequest>;

/**
 * @generated from message isuxportal.proto.services.admin.UpdateTeamResponse
 */
export declare type UpdateTeamResponse = Message<"isuxportal.proto.services.admin.UpdateTeamResponse"> & {
};

/**
 * Describes the message isuxportal.proto.services.admin.UpdateTeamResponse.
 * Use `create(UpdateTeamResponseSchema)` to create a new message.
 */
export declare const UpdateTeamResponseSchema: GenMessage<UpdateTeamResponse>;

