// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/admin/teams.proto (package isuxportal.proto.services.admin, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_team } from "../../resources/team_pb";
import { file_isuxportal_resources_contestant } from "../../resources/contestant_pb";

/**
 * Describes the file isuxportal/services/admin/teams.proto.
 */
export const file_isuxportal_services_admin_teams = /*@__PURE__*/
  fileDesc("CiVpc3V4cG9ydGFsL3NlcnZpY2VzL2FkbWluL3RlYW1zLnByb3RvEh9pc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLmFkbWluIhAKDkxpc3RUZWFtc1F1ZXJ5IpMCChFMaXN0VGVhbXNSZXNwb25zZRJOCgV0ZWFtcxgBIAMoCzI/LmlzdXhwb3J0YWwucHJvdG8uc2VydmljZXMuYWRtaW4uTGlzdFRlYW1zUmVzcG9uc2UuVGVhbUxpc3RJdGVtGq0BCgxUZWFtTGlzdEl0ZW0SDwoHdGVhbV9pZBgBIAEoAxIMCgRuYW1lGAIgASgJEhQKDG1lbWJlcl9uYW1lcxgDIAMoCRIbChNmaW5hbF9wYXJ0aWNpcGF0aW9uGAQgASgIEhIKCmlzX3N0dWRlbnQYBSABKAgSEQoJd2l0aGRyYXduGAYgASgIEhQKDGRpc3F1YWxpZmllZBgHIAEoCBIOCgZoaWRkZW4YCCABKAgiGgoMR2V0VGVhbVF1ZXJ5EgoKAmlkGAEgASgDIkEKD0dldFRlYW1SZXNwb25zZRIuCgR0ZWFtGAEgASgLMiAuaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMuVGVhbSIdCg9VcGRhdGVUZWFtUXVlcnkSCgoCaWQYASABKAMigAEKEVVwZGF0ZVRlYW1SZXF1ZXN0Ei4KBHRlYW0YASABKAsyIC5pc3V4cG9ydGFsLnByb3RvLnJlc291cmNlcy5UZWFtEjsKC2NvbnRlc3RhbnRzGAIgAygLMiYuaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMuQ29udGVzdGFudCIUChJVcGRhdGVUZWFtUmVzcG9uc2VCqAIKI2NvbS5pc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLmFkbWluQgpUZWFtc1Byb3RvUAFaVWdpdGh1Yi5jb20vaXN1Y29uL2lzdWNvbjE0LXBvcnRhbC9zdXBlcnZpc29yL2R1bW15YmVuY2gvZ2VuL2lzdXhwb3J0YWwvc2VydmljZXMvYWRtaW6iAgRJUFNBqgIfSXN1eHBvcnRhbC5Qcm90by5TZXJ2aWNlcy5BZG1pbsoCH0lzdXhwb3J0YWxcUHJvdG9cU2VydmljZXNcQWRtaW7iAitJc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXEFkbWluXEdQQk1ldGFkYXRh6gIiSXN1eHBvcnRhbDo6UHJvdG86OlNlcnZpY2VzOjpBZG1pbmIGcHJvdG8z", [file_isuxportal_resources_team, file_isuxportal_resources_contestant]);

/**
 * Describes the message isuxportal.proto.services.admin.ListTeamsQuery.
 * Use `create(ListTeamsQuerySchema)` to create a new message.
 */
export const ListTeamsQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_teams, 0);

/**
 * Describes the message isuxportal.proto.services.admin.ListTeamsResponse.
 * Use `create(ListTeamsResponseSchema)` to create a new message.
 */
export const ListTeamsResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_teams, 1);

/**
 * Describes the message isuxportal.proto.services.admin.ListTeamsResponse.TeamListItem.
 * Use `create(ListTeamsResponse_TeamListItemSchema)` to create a new message.
 */
export const ListTeamsResponse_TeamListItemSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_teams, 1, 0);

/**
 * Describes the message isuxportal.proto.services.admin.GetTeamQuery.
 * Use `create(GetTeamQuerySchema)` to create a new message.
 */
export const GetTeamQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_teams, 2);

/**
 * Describes the message isuxportal.proto.services.admin.GetTeamResponse.
 * Use `create(GetTeamResponseSchema)` to create a new message.
 */
export const GetTeamResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_teams, 3);

/**
 * Describes the message isuxportal.proto.services.admin.UpdateTeamQuery.
 * Use `create(UpdateTeamQuerySchema)` to create a new message.
 */
export const UpdateTeamQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_teams, 4);

/**
 * Describes the message isuxportal.proto.services.admin.UpdateTeamRequest.
 * Use `create(UpdateTeamRequestSchema)` to create a new message.
 */
export const UpdateTeamRequestSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_teams, 5);

/**
 * Describes the message isuxportal.proto.services.admin.UpdateTeamResponse.
 * Use `create(UpdateTeamResponseSchema)` to create a new message.
 */
export const UpdateTeamResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_teams, 6);

