// @generated by protoc-gen-es v2.0.0
// @generated from file isuxportal/services/admin/unprepared_stats.proto (package isuxportal.proto.services.admin, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_isuxportal_resources_team } from "../../resources/team_pb";

/**
 * Describes the file isuxportal/services/admin/unprepared_stats.proto.
 */
export const file_isuxportal_services_admin_unprepared_stats = /*@__PURE__*/
  fileDesc("CjBpc3V4cG9ydGFsL3NlcnZpY2VzL2FkbWluL3VucHJlcGFyZWRfc3RhdHMucHJvdG8SH2lzdXhwb3J0YWwucHJvdG8uc2VydmljZXMuYWRtaW4iFQoTR2V0U1NIS2V5U3RhdHNRdWVyeSLiAQoWR2V0U1NIS2V5U3RhdHNSZXNwb25zZRJdCgVpdGVtcxgBIAMoCzJOLmlzdXhwb3J0YWwucHJvdG8uc2VydmljZXMuYWRtaW4uR2V0U1NIS2V5U3RhdHNSZXNwb25zZS5TU0hLZXlVbnJlZ2lzdGVyZWRUZWFtGmkKFlNTSEtleVVucmVnaXN0ZXJlZFRlYW0SLgoEdGVhbRgBIAEoCzIgLmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzLlRlYW0SHwoXdW5yZWdpc3RlcmVkX21lbWJlcl9pZHMYAiADKAMiFgoUR2V0RGlzY29yZFN0YXRzUXVlcnki3gEKF0dldERpc2NvcmRTdGF0c1Jlc3BvbnNlElwKBWl0ZW1zGAEgAygLMk0uaXN1eHBvcnRhbC5wcm90by5zZXJ2aWNlcy5hZG1pbi5HZXREaXNjb3JkU3RhdHNSZXNwb25zZS5EaXNjb3JkTm90Sm9pbmVkVGVhbRplChREaXNjb3JkTm90Sm9pbmVkVGVhbRIuCgR0ZWFtGAEgASgLMiAuaXN1eHBvcnRhbC5wcm90by5yZXNvdXJjZXMuVGVhbRIdChVub3Rfam9pbmVkX21lbWJlcl9pZHMYAiADKAMiFwoVR2V0RW52Q2hlY2tTdGF0c1F1ZXJ5IksKGEdldEVudkNoZWNrU3RhdHNSZXNwb25zZRIvCgVpdGVtcxgBIAMoCzIgLmlzdXhwb3J0YWwucHJvdG8ucmVzb3VyY2VzLlRlYW1CsgIKI2NvbS5pc3V4cG9ydGFsLnByb3RvLnNlcnZpY2VzLmFkbWluQhRVbnByZXBhcmVkU3RhdHNQcm90b1ABWlVnaXRodWIuY29tL2lzdWNvbi9pc3Vjb24xNC1wb3J0YWwvc3VwZXJ2aXNvci9kdW1teWJlbmNoL2dlbi9pc3V4cG9ydGFsL3NlcnZpY2VzL2FkbWluogIESVBTQaoCH0lzdXhwb3J0YWwuUHJvdG8uU2VydmljZXMuQWRtaW7KAh9Jc3V4cG9ydGFsXFByb3RvXFNlcnZpY2VzXEFkbWlu4gIrSXN1eHBvcnRhbFxQcm90b1xTZXJ2aWNlc1xBZG1pblxHUEJNZXRhZGF0YeoCIklzdXhwb3J0YWw6OlByb3RvOjpTZXJ2aWNlczo6QWRtaW5iBnByb3RvMw", [file_isuxportal_resources_team]);

/**
 * Describes the message isuxportal.proto.services.admin.GetSSHKeyStatsQuery.
 * Use `create(GetSSHKeyStatsQuerySchema)` to create a new message.
 */
export const GetSSHKeyStatsQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_unprepared_stats, 0);

/**
 * Describes the message isuxportal.proto.services.admin.GetSSHKeyStatsResponse.
 * Use `create(GetSSHKeyStatsResponseSchema)` to create a new message.
 */
export const GetSSHKeyStatsResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_unprepared_stats, 1);

/**
 * Describes the message isuxportal.proto.services.admin.GetSSHKeyStatsResponse.SSHKeyUnregisteredTeam.
 * Use `create(GetSSHKeyStatsResponse_SSHKeyUnregisteredTeamSchema)` to create a new message.
 */
export const GetSSHKeyStatsResponse_SSHKeyUnregisteredTeamSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_unprepared_stats, 1, 0);

/**
 * Describes the message isuxportal.proto.services.admin.GetDiscordStatsQuery.
 * Use `create(GetDiscordStatsQuerySchema)` to create a new message.
 */
export const GetDiscordStatsQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_unprepared_stats, 2);

/**
 * Describes the message isuxportal.proto.services.admin.GetDiscordStatsResponse.
 * Use `create(GetDiscordStatsResponseSchema)` to create a new message.
 */
export const GetDiscordStatsResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_unprepared_stats, 3);

/**
 * Describes the message isuxportal.proto.services.admin.GetDiscordStatsResponse.DiscordNotJoinedTeam.
 * Use `create(GetDiscordStatsResponse_DiscordNotJoinedTeamSchema)` to create a new message.
 */
export const GetDiscordStatsResponse_DiscordNotJoinedTeamSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_unprepared_stats, 3, 0);

/**
 * Describes the message isuxportal.proto.services.admin.GetEnvCheckStatsQuery.
 * Use `create(GetEnvCheckStatsQuerySchema)` to create a new message.
 */
export const GetEnvCheckStatsQuerySchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_unprepared_stats, 4);

/**
 * Describes the message isuxportal.proto.services.admin.GetEnvCheckStatsResponse.
 * Use `create(GetEnvCheckStatsResponseSchema)` to create a new message.
 */
export const GetEnvCheckStatsResponseSchema = /*@__PURE__*/
  messageDesc(file_isuxportal_services_admin_unprepared_stats, 5);

