name: deploy benchmarker
on:
  push:
    branches:
      - feat/deploy.bench 
  workflow_dispatch:
    inputs:
      TAG:
        description: 'tag'
        required: true
jobs:
  bench:
    - uses: actions/checkout@v4
    - name: Configure AWS credentials from IAM Role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_DEPLOY_ROLE_ARN }}
        aws-region: ap-northeast-1
    - uses: kayac/ecspresso@v2
      with:
        version: latest 
    - name: deploy
      working-directory: ecs
      run: |
        ecspresso deploy --config benchmarker.yml
      env:
        TAG: ${{ github.event.inputs.TAG || 'latest' }}
        ENV: stg
