name: NOP action on self-hosted runner
on:
  push:
    branches:
      - feat/deploy.bench 
jobs:
  NOP-Job:
    runs-on: codebuild-portal-github-actions-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "nop"
